/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi } from 'vitest';
import { normalizeTags } from './normalizeTags';

describe('normalizeTags', () => {
  it('should handle happy path', () => {
    const result = normalizeTags(['JavaScript', 'Node.js']);
    expect(Array.isArray(result)).toBe(true);
    expect(result.length).toBe(2);
    expect(result).toEqual(expect.arrayContaining(['javascript', 'node.js']));
  });

  it('should handle edge case', () => {
    const result = normalizeTags(['', ' ', '\t']);
    expect(Array.isArray(result)).toBe(true);
    // Assuming empty or whitespace tags are filtered out
    expect(result.length).toBe(0);
  });

  it('should handle null/empty', () => {
    expect(normalizeTags()).toEqual([]);
    expect(normalizeTags(undefined)).toEqual([]);
    expect(normalizeTags(null as any)).toEqual([]);
    expect(normalizeTags('')).toEqual([]);
    expect(normalizeTags(0 as any)).toEqual([]);
  });
});

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

describe('sortNotesByUpdatedAt', () => {
  // Mock notes with different updatedAt timestamps
  const mockNotes = [
    { id: '1', title: 'Note 1', updatedAt: '2023-01-03T10:00:00Z' },
    { id: '2', title: 'Note 2', updatedAt: '2023-01-01T10:00:00Z' },
    { id: '3', title: 'Note 3', updatedAt: '2023-01-02T10:00:00Z' },
  ];

  // Import the function being tested
  // Assuming it's exported from a module
  let sortNotesByUpdatedAt: (notes?: any[]) => any[];
  
  beforeEach(async () => {
    const module = await import('./notes');
    sortNotesByUpdatedAt = module.sortNotesByUpdatedAt;
  });

  it('should sort notes by updatedAt in descending order (happy path)', () => {
    const result = sortNotesByUpdatedAt(mockNotes);
    
    // Most recent date should be first
    expect(result[0].id).toBe('1');
    expect(result[0].updatedAt).toBe('2023-01-03T10:00:00Z');
    
    expect(result[1].id).toBe('3');
    expect(result[1].updatedAt).toBe('2023-01-02T10:00:00Z');
    
    expect(result[2].id).toBe('2');
    expect(result[2].updatedAt).toBe('2023-01-01T10:00:00Z');
  });

  it('should handle edge case with notes having identical updatedAt timestamps', () => {
    const notesWithSameTimestamp = [
      { id: '1', title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
      { id: '2', title: 'Note B', updatedAt: '2023-01-01T10:00:00Z' },
      { id: '3', title: 'Note C', updatedAt: '2023-01-01T10:00:00Z' },
    ];
    
    const result = sortNotesByUpdatedAt(notesWithSameTimestamp);
    
    expect(result).toHaveLength(3);
    // All notes should still be present
    expect(result.map(n => n.id)).toContain('1');
    expect(result.map(n => n.id)).toContain('2');
    expect(result.map(n => n.id)).toContain('3');
  });

  it('should handle null/empty input gracefully', () => {
    // Test with null
    expect(sortNotesByUpdatedAt(null)).toEqual([]);
    
    // Test with undefined
    expect(sortNotesByUpdatedAt(undefined)).toEqual([]);
    
    // Test with empty array
    expect(sortNotesByUpdatedAt([])).toEqual([]);
    
    // Test with default parameter (no argument passed)
    expect(sortNotesByUpdatedAt()).toEqual([]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { matchesSearchQuery } from './matchesSearchQuery';

describe('matchesSearchQuery', () => {
  beforeEach(() => {
    // No external dependencies to mock for this function
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path where note contains the query (case‑insensitive)', () => {
    const note = 'Today I learned about Vitest testing framework.';
    const query = 'vitest';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  it('should handle edge case with empty query string (should match any note)', () => {
    const note = 'Any content works here.';
    const query = '';
    const result = matchesSearchQuery(note, query);
    // Assuming an empty query matches everything
    expect(result).toBe(true);
  });

  it('should handle null/empty inputs gracefully', () => {
    // null note
    expect(matchesSearchQuery(null as any, 'test')).toBe(false);
    // undefined note
    expect(matchesSearchQuery(undefined as any, 'test')).toBe(false);
    // empty note string
    expect(matchesSearchQuery('', 'test')).toBe(false);

    // null query
    const note = 'Sample note';
    expect(matchesSearchQuery(note, null as any)).toBe(true); // empty query matches
    // undefined query
    expect(matchesSearchQuery(note, undefined as any)).toBe(true);
    // numeric zero as query
    expect(matchesSearchQuery(note, 0 as any)).toBe(true);
  });
});

# ── Tests for countWords  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { countWords } from './countWords';

describe('countWords', () => {
  it('should handle happy path', () => {
    const input = 'Hello world, this is a test.';
    const result = countWords(input);
    expect(result).toBe(6);
  });

  it('should handle edge case', () => {
    const input = '  Leading and trailing   spaces  ';
    const result = countWords(input);
    expect(result).toBe(4);
  });

  it('should handle null/empty', () => {
    const inputs = [null, undefined, '', 0 as any];
    const expected = [0, 0, 0, 0];
    inputs.forEach((input, index) => {
      const result = countWords(input as unknown as string);
      expect(result).toBe(expected[index]);
    });
  });
});