/**
 * Auto-generated tests for src/components/NoteItem.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteItem';



# ── Tests for NoteItem  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import NoteItem from '../src/NoteItem';

describe('NoteItem', () => {
  const mockOnSelect = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path', () => {
    const note = { id: '1', title: 'Test Note', content: 'Hello world' };
    render(<NoteItem note={note} isSelected={false} onSelect={mockOnSelect} />);
    expect(screen.getByText('Test Note')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button'));
    expect(mockOnSelect).toHaveBeenCalledWith(note.id);
  });

  it('should handle edge case when note has empty title', () => {
    const note = { id: '2', title: '', content: 'No title note' };
    render(<NoteItem note={note} isSelected={true} onSelect={mockOnSelect} />);
    expect(screen.getByText('(No Title)')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button'));
    expect(mockOnSelect).toHaveBeenCalledWith(note.id);
  });

  it('should handle null/empty props', () => {
    render(<NoteItem note={null as any} isSelected={null as any} onSelect={mockOnSelect} />);
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
    expect(mockOnSelect).not.toHaveBeenCalled();
  });
});

# ── Tests for formatDate  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { formatDate } from './path/to/module'; // adjust the import path accordingly

describe('formatDate', () => {
  // Happy path: valid ISO string returns formatted date (YYYY-MM-DD)
  it('should handle happy path with a standard ISO string', () => {
    const iso = '2023-07-15T13:45:30.000Z';
    const result = formatDate(iso);
    expect(result).toBe('2023-07-15');
  });

  // Edge case: ISO string without time component
  it('should handle edge case with date‑only ISO string', () => {
    const iso = '1999-12-31';
    const result = formatDate(iso);
    expect(result).toBe('1999-12-31');
  });

  // Null / empty / undefined / zero handling
  it('should handle null/empty inputs gracefully', () => {
    const cases = [null, undefined, '', 0];
    cases.forEach((input) => {
      // Assuming the function returns an empty string for invalid inputs
      const result = (formatDate as any)(input);
      expect(result).toBe('');
    });
  });
});

# ── Tests for truncateContent  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { truncateContent } from './utils';

describe('truncateContent', () => {
  // Happy path: content longer than maxLength gets truncated
  it('should handle happy path when content exceeds maxLength', () => {
    const longText = 'a'.repeat(100);
    const result = truncateContent(longText, 80);
    // Expect the result length to be at most maxLength (including possible ellipsis)
    expect(result.length).toBeLessThanOrEqual(80);
    // The returned string should start with the original content prefix
    expect(result.startsWith('a'.repeat(80).slice(0, result.length))).toBe(true);
  });

  // Edge case: content exactly at the boundary
  it('should handle edge case when content length equals maxLength', () => {
    const exactText = 'b'.repeat(80);
    const result = truncateContent(exactText, 80);
    expect(result).toBe(exactText);
    expect(result.length).toBe(80);
  });

  // Null / empty handling
  it('should handle null/empty inputs gracefully', () => {
    // null
    // @ts-expect-error testing runtime behavior with null
    expect(truncateContent(null, 80)).toBe('');
    // undefined
    // @ts-expect-error testing runtime behavior with undefined
    expect(truncateContent(undefined, 80)).toBe('');
    // empty string
    expect(truncateContent('', 80)).toBe('');
    // zero maxLength
    const text = 'sample';
    const result = truncateContent(text, 0);
    expect(result).toBe('');
    expect(result.length).toBe(0);
  });
});

# ── Tests for handleDelete  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { handleDelete } from './handleDelete';

// Mock any side‑effects the function might use (e.g., DOM APIs, external services)
const preventDefaultMock = vi.fn();
const stopPropagationMock = vi.fn();

beforeEach(() => {
  preventDefaultMock.mockClear();
  stopPropagationMock.mockClear();
});

describe('handleDelete', () => {
  it('should handle happy path when a valid event is provided', () => {
    const mockEvent = {
      preventDefault: preventDefaultMock,
      stopPropagation: stopPropagationMock,
      // add any other properties the implementation might read
      target: { dataset: { id: '123' } },
    } as unknown as Event;

    // Assuming the function returns something meaningful on success,
    // adjust the expectation to match the real behavior.
    const result = handleDelete(mockEvent);
    expect(preventDefaultMock).toHaveBeenCalledOnce();
    expect(stopPropagationMock).toHaveBeenCalledOnce();

    // Example generic expectation; replace with actual return value check.
    expect(result).toBeUndefined();
  });

  it('should handle edge case with missing dataset id but valid event object', () => {
    const mockEvent = {
      preventDefault: preventDefaultMock,
      stopPropagation: stopPropagationMock,
      target: { dataset: {} }, // id missing
    } as unknown as Event;

    const result = handleDelete(mockEvent);
    expect(preventDefaultMock).toHaveBeenCalledOnce();
    expect(stopPropagationMock).toHaveBeenCalledOnce();

    // Edge case may result in a no‑op or a specific return; adjust as needed.
    expect(result).toBeUndefined();
  });

  it('should handle null/empty/undefined event inputs gracefully', () => {
    // Null input
    expect(() => handleDelete(null as any)).not.toThrow();

    // Undefined input
    expect(() => handleDelete(undefined as any)).not.toThrow();

    // Empty object (no methods)
    expect(() => handleDelete({} as any)).not.toThrow();

    // Zero as event (unlikely but testing numeric falsy)
    expect(() => handleDelete(0 as any)).not.toThrow();
  });
});