/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteList';



# ── Tests for NoteList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup } from '@testing-library/react';
import React from 'react';
import NoteList from '@/components/NoteList';

// Mock any child components or modules that NoteList might import
vi.mock('@/components/NoteItem', () => ({
  default: (props: any) => (
    <div data-testid="note-item" onClick={() => props.onClick && props.onClick()}>
      {props.title || 'Untitled'}
    </div>
  ),
}));

describe('NoteList Component', () => {
  const mockOnSelectNote = vi.fn();

  afterEach(() => {
    vi.clearAllMocks();
    cleanup();
  });

  // Happy path: renders a list of notes and calls onSelectNote when a note is clicked
  it('should handle happy path: render notes and respond to selection', () => {
    const notes = [
      { id: '1', title: 'Note 1' },
      { id: '2', title: 'Note 2' },
    ];

    render(
      <NoteList onSelectNote={mockOnSelectNote} selectedNoteId="1">
        {notes.map((note) => (
          <div key={note.id} data-testid={`note-${note.id}`} onClick={() => mockOnSelectNote(note.id)}>
            {note.title}
          </div>
        ))}
      </NoteList>
    );

    // Verify notes are in the document
    notes.forEach((note) => {
      expect(screen.getByText(note.title)).toBeInTheDocument();
    });

    // Simulate clicking the second note
    fireEvent.click(screen.getByTestId('note-2'));
    expect(mockOnSelectNote).toHaveBeenCalledOnce();
    expect(mockOnSelectNote).toHaveBeenCalledWith('2');
  });

  // Edge case: renders correctly when there is only one note and it is selected
  it('should handle edge case: single note selected', () => {
    const notes = [{ id: '42', title: 'Only Note' }];

    render(
      <NoteList onSelectNote={mockOnSelectNote} selectedNoteId="42">
        {notes.map((note) => (
          <div key={note.id} data-testid={`note-${note.id}`} onClick={() => mockOnSelectNote(note.id)}>
            {note.title}
          </div>
        ))}
      </NoteList>
    );

    const noteElement = screen.getByTestId('note-42');
    expect(noteElement).toBeInTheDocument();
    expect(noteElement).toHaveTextContent('Only Note');

    // Click the single note
    fireEvent.click(noteElement);
    expect(mockOnSelectNote).toHaveBeenCalledOnce();
    expect(mockOnSelectNote).toHaveBeenCalledWith('42');
  });

  // Null/empty inputs: component should render without crashing and not call handler
  it('should handle null/empty inputs gracefully', () => {
    render(<NoteList onSelectNote={null as any} selectedNoteId={null as any} />);

    // No notes should be rendered, but component should not throw
    const noteItems = screen.queryAllByTestId('note-item');
    expect(noteItems.length).toBe(0);

    // Ensure the onSelectNote handler is not called
    expect(mockOnSelectNote).not.toHaveBeenCalled();
  });
});