/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { normalizeTags } from './path/to/your/module';

describe('normalizeTags', () => {
  beforeEach(() => {
    // Reset any mocks if needed
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path with typical tag strings', () => {
    const input = ['JavaScript', '  TypeScript  ', 'NodeJS'];
    const result = normalizeTags(input);
    // Expected behavior: trim whitespace and lowercase each tag
    expect(result).toEqual(['javascript', 'typescript', 'nodejs']);
  });

  it('should handle edge case with duplicate and mixed‑case tags', () => {
    const input = ['React', 'react', ' REACT ', 'Vue'];
    const result = normalizeTags(input);
    // Expected behavior: deduplicate after normalization
    expect(result).toEqual(['react', 'vue']);
  });

  it('should handle null/empty/invalid inputs gracefully', () => {
    // null
    expect(normalizeTags(null as any)).toEqual([]);
    // undefined
    expect(normalizeTags(undefined as any)).toEqual([]);
    // empty string (should be treated as a non‑array)
    expect(normalizeTags('' as any)).toEqual([]);
    // number 0 (should be treated as a non‑array)
    expect(normalizeTags(0 as any)).toEqual([]);
    // empty array
    expect(normalizeTags()).toEqual([]);
  });
});

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

describe('sortNotesByUpdatedAt', () => {
  let sortNotesByUpdatedAt: (notes?: any[]) => any[];

  beforeEach(() => {
    // Import the function lazily to allow mocking if needed
    // @ts-ignore
    import.meta.globEager = vi.fn();
    // @ts-ignore
    import('path/to/module').then((m) => {
      sortNotesByUpdatedAt = m.default ? m.default : m.sortNotesByUpdatedAt;
    });
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path with sorted and unsorted notes', () => {
    const notes = [
      { id: 1, updatedAt: new Date('2023-01-01').getTime() },
      { id: 2, updatedAt: new Date('2023-03-01').getTime() },
      { id: 3, updatedAt: new Date('2023-02-01').getTime() },
    ];
    const result = sortNotesByUpdatedAt(notes);
    expect(result).toEqual([
      { id: 2, updatedAt: new Date('2023-03-01').getTime() },
      { id: 3, updatedAt: new Date('2023-02-01').getTime() },
      { id: 1, updatedAt: new Date('2023-01-01').getTime() },
    ]);
  });

  it('should handle edge case with notes having identical timestamps', () => {
    const timestamp = new Date('2023-04-01').getTime();
    const notes = [
      { id: 1, updatedAt: timestamp },
      { id: 2, updatedAt: timestamp },
      { id: 3, updatedAt: timestamp },
    ];
    const result = sortNotesByUpdatedAt(notes);
    // Order should be preserved for equal timestamps (stable sort)
    expect(result).toEqual(notes);
  });

  it('should handle null/empty inputs', () => {
    expect(sortNotesByUpdatedAt()).toEqual([]);
    expect(sortNotesByUpdatedAt(null as any)).toEqual([]);
    expect(sortNotesByUpdatedAt(undefined as any)).toEqual([]);
    expect(sortNotesByUpdatedAt([])).toEqual([]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect, vi } from 'vitest';

// Assuming the function is exported from a module named `searchUtils`
import { matchesSearchQuery } from '@/utils/searchUtils';

describe('matchesSearchQuery', () => {
  it('should handle happy path: return true when note matches query', () => {
    const note = { title: 'Meeting Notes', content: 'Discuss project timeline and milestones.' };
    const query = 'project timeline';
    const result = matchesSearchQuery(note, query);
    expect(result).toBeTypeOf('boolean');
    expect(result).toBe(true);
  });

  it('should handle edge case: empty string query returns true', () => {
    const note = { title: 'Todo', content: 'Buy milk' };
    const result = matchesSearchQuery(note, '');
    expect(result).toBeTypeOf('boolean');
    expect(result).toBe(true);
  });

  it('should handle null/empty inputs: return false on null or undefined note', () => {
    const result1 = matchesSearchQuery(null as unknown as any, 'test');
    const result2 = matchesSearchQuery(undefined as unknown as any, 'test');
    const result3 = matchesSearchQuery({} as any, 'test');
    expect(result1).toBeTypeOf('boolean');
    expect(result1).toBe(false);
    expect(result2).toBeTypeOf('boolean');
    expect(result2).toBe(false);
    expect(result3).toBeTypeOf('boolean');
    expect(result3).toBe(false);
  });
});

# ── Tests for countWords  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { countWords } from './countWords';

describe('countWords', () => {
  beforeEach(() => {
    // No external dependencies to mock for this pure function
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path with a normal sentence', () => {
    const text = 'The quick brown fox jumps over the lazy dog';
    const result = countWords(text);
    expect(result).toBe(9);
  });

  it('should handle edge case with multiple spaces and newline characters', () => {
    const text = '   Hello   world \n this   is   a test  ';
    const result = countWords(text);
    // Words: Hello, world, this, is, a, test => 6
    expect(result).toBe(6);
  });

  it('should handle null/empty inputs gracefully', () => {
    // undefined
    expect(countWords(undefined as any)).toBe(0);
    // null
    expect(countWords(null as any)).toBe(0);
    // empty string
    expect(countWords('')).toBe(0);
    // numeric zero (should be treated as string "0")
    expect(countWords(0 as any)).toBe(1);
  });
});