/**
 * Auto-generated tests for src/hooks/useNotesList.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../useNotesList';



# ── Tests for useNotesList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

describe('useNotesList', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path - return list of notes when notes exist', () => {
    const mockNotes = [
      { id: '1', title: 'Note 1', content: 'Content 1' },
      { id: '2', title: 'Note 2', content: 'Content 2' },
    ];
    
    const mockNoteService = {
      getAll: vi.fn().mockResolvedValue(mockNotes),
    };
    
    vi.mock('../services/noteService', () => ({
      default: mockNoteService,
    }));

    const useNotesList = async () => {
      const notes = await mockNoteService.getAll();
      return notes;
    };

    expect(useNotesList()).resolves.toHaveLength(2);
    expect(useNotesList()).resolves.toEqual(mockNotes);
  });

  it('should handle edge case - return empty array when single note is deleted', async () => {
    const mockNotes = [{ id: '1', title: 'Single Note', content: 'Content' }];
    
    const mockNoteService = {
      getAll: vi.fn().mockResolvedValue(mockNotes),
      delete: vi.fn().mockResolvedValue(undefined),
    };
    
    vi.mock('../services/noteService', () => ({
      default: mockNoteService,
    }));

    const useNotesList = async () => {
      await mockNoteService.delete('1');
      const notes = await mockNoteService.getAll();
      return notes;
    };

    const result = await useNotesList();
    expect(mockNoteService.delete).toHaveBeenCalledWith('1');
    expect(result).toHaveLength(1);
  });

  it('should handle null/empty - return empty array when no notes exist', async () => {
    const mockNoteService = {
      getAll: vi.fn().mockResolvedValue([]),
    };
    
    vi.mock('../services/noteService', () => ({
      default: mockNoteService,
    }));

    const useNotesList = async () => {
      const notes = await mockNoteService.getAll();
      return notes;
    };

    const result = await useNotesList();
    expect(result).toEqual([]);
    expect(result).toHaveLength(0);
    expect(mockNoteService.getAll).toHaveBeenCalled();
  });
});