/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { normalizeTags } from './utils';

describe('normalizeTags', () => {
  beforeEach(() => {
    // Reset any global state if needed
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path with typical tags array', () => {
    const input = ['JavaScript', '  Typescript  ', 'nodejs'];
    const result = normalizeTags(input);
    // Assuming the function trims whitespace and lower‑cases tags
    expect(result).toEqual(['javascript', 'typescript', 'nodejs']);
  });

  it('should handle edge case with empty strings and duplicate tags', () => {
    const input = ['', 'React', 'react', '  '];
    const result = normalizeTags(input);
    // Expect empty strings removed, duplicates consolidated, trimmed and lower‑cased
    expect(result).toEqual(['react']);
  });

  it('should handle null/empty inputs gracefully', () => {
    // null input
    // @ts-expect-error testing runtime behavior with null
    expect(() => normalizeTags(null)).not.toThrow();
    // undefined input (function default)
    expect(normalizeTags(undefined)).toEqual([]);
    // empty string input (invalid type, should be treated as empty array)
    // @ts-expect-error testing runtime behavior with wrong type
    expect(() => normalizeTags('')).not.toThrow();
    // numeric zero input (invalid type)
    // @ts-expect-error testing runtime behavior with wrong type
    expect(() => normalizeTags(0)).not.toThrow();
  });
});

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { sortNotesByUpdatedAt } from '../src/sortNotesByUpdatedAt';

describe('sortNotesByUpdatedAt', () => {
  it('should handle happy path with multiple notes', () => {
    const notes = [
      { id: 1, updatedAt: '2023-01-01T10:00:00Z' },
      { id: 2, updatedAt: '2023-01-03T12:00:00Z' },
      { id: 3, updatedAt: '2023-01-02T08:30:00Z' },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    expect(sorted).toEqual([
      { id: 2, updatedAt: '2023-01-03T12:00:00Z' },
      { id: 3, updatedAt: '2023-01-02T08:30:00Z' },
      { id: 1, updatedAt: '2023-01-01T10:00:00Z' },
    ]);
  });

  it('should handle edge case with same timestamps', () => {
    const notes = [
      { id: 1, updatedAt: '2023-01-01T00:00:00Z' },
      { id: 2, updatedAt: '2023-01-01T00:00:00Z' },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    // Order should be stable (original order preserved)
    expect(sorted).toEqual([
      { id: 1, updatedAt: '2023-01-01T00:00:00Z' },
      { id: 2, updatedAt: '2023-01-01T00:00:00Z' },
    ]);
  });

  it('should handle null/empty inputs gracefully', () => {
    // @ts-ignore – testing runtime behaviour with undefined
    expect(sortNotesByUpdatedAt(undefined)).toEqual([]);
    // @ts-ignore – testing runtime behaviour with null
    expect(sortNotesByUpdatedAt(null)).toEqual([]);
    expect(sortNotesByUpdatedAt([])).toEqual([]);
    expect(sortNotesByUpdatedAt('')).toEqual([]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assuming matchesSearchQuery is exported from the module './search'
import { matchesSearchQuery } from './search';

describe('matchesSearchQuery', () => {
  // Happy path: note matches query in title
  it('should handle happy path: match in title', () => {
    const note = { title: 'Meeting notes', content: 'Discuss project timeline' };
    const query = 'meeting';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  // Edge case: query is very short but still valid
  it('should handle edge case: short query that matches part of content', () => {
    const note = { title: 'Shopping', content: 'Eggs, milk, bread' };
    const query = 'e';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  // Null/empty: note or query is null/empty
  it('should handle null/empty: empty query returns true', () => {
    const note = { title: 'Todo', content: 'Finish report' };
    const result = matchesSearchQuery(note, '');
    expect(result).toBe(true);
  });

  it('should handle null/empty: null note returns false', () => {
    const result = matchesSearchQuery(null as any, 'test');
    expect(result).toBe(false);
  });

  it('should handle null/empty: undefined query treated as empty', () => {
    const note = { title: 'Draft', content: 'Draft content' };
    const result = matchesSearchQuery(note, undefined as any);
    expect(result).toBe(true);
  });
});

# ── Tests for countWords  ──

import { describe, it, expect } from 'vitest';

function countWords(text = '') {
  if (!text) return 0;
  return text.trim().split(/\s+/).filter(Boolean).length;
}

describe('countWords', () => {
  it('should handle happy path – basic sentence', () => {
    const result = countWords('Hello world this is a test');
    expect(result).toBe(7);
  });

  it('should handle edge case – multiple spaces and punctuation', () => {
    const result = countWords('  Multiple   spaces, and, punctuation!  ');
    expect(result).toBe(5); // "Multiple", "spaces,", "and,", "punctuation!"
  });

  it('should handle null/empty – undefined, null, empty string, 0', () => {
    expect(countWords()).toBe(0);
    // @ts-ignore
    expect(countWords(undefined)).toBe(0);
    // @ts-ignore
    expect(countWords(null)).toBe(0);
    expect(countWords('')).toBe(0);
    expect(countWords('0')).toBe(1);
  });
});