/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// Import the module under test — path is relative to tests/unit/
// import { noteUtils } from '../../src/modules/noteUtils';



// ── Tests for normalizeTags  ──



// ── Tests for sortNotesByUpdatedAt  ──



// ── Tests for matchesSearchQuery  ──

import { describe, it, expect } from 'vitest';
import { matchesSearchQuery } from '../../src/modules/noteUtils';

describe('matchesSearchQuery', () => {
  // Test 1: Happy path – query matches note title
  it('should handle happy path with matching title', () => {
    const note = { title: 'Meeting Notes', content: 'Discuss project timeline.' };
    const query = 'meeting';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  // Test 2: Edge case – query is a substring of the note content
  it('should handle edge case with substring in content', () => {
    const note = { title: 'Shopping List', content: 'Milk, Bread, Butter, and Honey' };
    const query = 'bread';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  // Test 3: Null/empty input handling
  it('should handle null/empty input values', () => {
    const note = { title: '', content: '' };
    const query = '';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(false);
  });
});

// ── Tests for countWords  ──

import { describe, it, expect } from 'vitest';
import { countWords } from '../../src/modules/noteUtils';

describe('countWords', () => {
  it('should handle happy path', () => {
    const text = 'Hello world! This is a test.';
    const result = countWords(text);
    expect(result).toBe(6);
  });

  it('should handle edge case', () => {
    const text = '  Leading and   multiple   spaces  ';
    const result = countWords(text);
    expect(result).toBe(5);
  });

  it('should handle null/empty', () => {
    expect(countWords()).toBe(0);
    expect(countWords('')).toBe(0);
    expect(countWords(null as unknown as string)).toBe(0);
    expect(countWords(undefined as unknown as string)).toBe(0);
  });
});