/**
 * Auto-generated tests for src/components/NoteItem.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteItem';



# ── Tests for NoteItem  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, fireEvent, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import NoteItem from '../src/components/NoteItem';

describe('NoteItem component', () => {
  const mockNote = { id: '1', title: 'Test Note', content: 'This is a test note.' };
  const mockOnSelect = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path: render note and invoke onSelect when clicked', () => {
    render(<NoteItem note={mockNote} isSelected={false} onSelect={mockOnSelect} />);

    expect(screen.getByText(mockNote.title)).toBeInTheDocument();
    expect(screen.getByText(mockNote.content)).toBeInTheDocument();

    const container = screen.getByRole('button', { name: /test note/i });
    fireEvent.click(container);

    expect(mockOnSelect).toHaveBeenCalledOnce();
    expect(mockOnSelect).toHaveBeenCalledWith(mockNote.id);
  });

  it('should handle edge case: render selected note style and still call onSelect', () => {
    render(<NoteItem note={mockNote} isSelected={true} onSelect={mockOnSelect} />);

    const container = screen.getByRole('button', { name: /test note/i });
    expect(container).toHaveClass('selected'); // assuming a CSS class is applied

    fireEvent.click(container);
    expect(mockOnSelect).toHaveBeenCalledOnce();
  });

  it('should handle null/empty: ignore rendering and not call onSelect', () => {
    // Test with null note
    render(<NoteItem note={null as any} isSelected={false} onSelect={mockOnSelect} />);
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
    expect(mockOnSelect).not.toHaveBeenCalled();

    // Test with empty string as title
    const emptyNote = { id: '2', title: '', content: '' };
    render(<NoteItem note={emptyNote} isSelected={false} onSelect={mockOnSelect} />);
    expect(screen.getByRole('button')).toBeInTheDocument();
    expect(mockOnSelect).not.toHaveBeenCalled();

    // Test with undefined onSelect
    render(<NoteItem note={mockNote} isSelected={false} onSelect={undefined as any} />);
    const button = screen.getByRole('button', { name: /test note/i });
    fireEvent.click(button);
    expect(mockOnSelect).not.toHaveBeenCalled();
  });
});

# ── Tests for formatDate  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

describe('formatDate', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('should handle happy path with valid ISO string', () => {
    const isoString = '2024-01-15T10:30:00.000Z';
    const result = formatDate(isoString);
    expect(result).toBe('January 15, 2024');
  });

  it('should handle edge case with different timezone offset', () => {
    const isoString = '2024-12-31T23:59:59.000+05:30';
    const result = formatDate(isoString);
    expect(result).toBe('December 31, 2024');
  });

  it('should handle null/empty input values', () => {
    expect(formatDate(null as any)).toBe('');
    expect(formatDate(undefined as any)).toBe('');
    expect(formatDate('')).toBe('');
    expect(formatDate(0 as any)).toBe('');
  });
});

# ── Tests for truncateContent  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { truncateContent } from './truncateContent';

describe('truncateContent', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path by returning content trimmed to the specified maxLength', () => {
    const content = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
    const maxLength = 20;
    const result = truncateContent(content, maxLength);
    expect(result).toBe(content.slice(0, maxLength));
  });

  it('should handle edge case when content length equals maxLength', () => {
    const content = 'ExactLengthString';
    const maxLength = content.length;
    const result = truncateContent(content, maxLength);
    expect(result).toBe(content);
  });

  it('should handle null/empty inputs gracefully', () => {
    // null input
    // @ts-expect-error testing runtime behavior with null
    expect(truncateContent(null, 10)).toBe('');
    // undefined input
    // @ts-expect-error testing runtime behavior with undefined
    expect(truncateContent(undefined, 10)).toBe('');
    // empty string
    expect(truncateContent('', 10)).toBe('');
    // zero maxLength
    const content = 'NonEmpty';
    expect(truncateContent(content, 0)).toBe('');
  });
});

# ── Tests for handleDelete  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

vi.mock('./noteService', () => ({
  deleteNote: vi.fn()
}));
import { deleteNote } from './noteService';
import { handleDelete } from './handleDelete';

describe('handleDelete', () => {
  const mockEvent = { preventDefault: vi.fn() } as unknown as Event;

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path when event is provided', () => {
    // Arrange
    const dummyNoteId = '123';
    mockEvent['target'] = { dataset: { noteId: dummyNoteId } };

    // Act
    handleDelete(mockEvent);

    // Assert
    expect(mockEvent.preventDefault).toHaveBeenCalledTimes(1);
    expect(deleteNote).toHaveBeenCalledWith(dummyNoteId);
  });

  it('should handle edge case when target dataset is missing', () => {
    // Arrange
    mockEvent['target'] = {};

    // Act
    handleDelete(mockEvent);

    // Assert
    expect(mockEvent.preventDefault).toHaveBeenCalledTimes(1);
    expect(deleteNote).not.toHaveBeenCalled();
  });

  it('should handle null/empty event', () => {
    // Act
    expect(() => handleDelete(null as unknown as Event)).not.toThrow();
    expect(() => handleDelete(undefined as unknown as Event)).not.toThrow();
  });
});