/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

// Assuming the function is exported from a module named './normalizeTags'
vi.mock('./normalizeTags', () => ({
  normalizeTags: vi.fn(),
}))
import { normalizeTags } from './normalizeTags'

describe('normalizeTags', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('should handle happy path', () => {
    ;(normalizeTags as any).mockReturnValue(['js', 'node'])
    const result = normalizeTags(['JS', 'node'])
    expect(result).toEqual(['js', 'node'])
  })

  it('should handle edge case', () => {
    // Edge case: duplicate tags + mixed case, should deduplicate and lowercase
    ;(normalizeTags as any).mockReturnValue(['react', 'redux'])
    const result = normalizeTags(['React', 'react', 'REDUX'])
    expect(result).toEqual(['react', 'redux'])
  })

  it('should handle null/empty', () => {
    // Null/empty situations: input null, undefined, empty array, empty string
    ;(normalizeTags as any).mockReturnValue([])
    const resultNull = normalizeTags(null as any)
    const resultUndefined = normalizeTags(undefined as any)
    const resultEmptyArray = normalizeTags([])
    const resultEmptyString = normalizeTags([''] as any)

    expect(resultNull).toEqual([])
    expect(resultUndefined).toEqual([])
    expect(resultEmptyArray).toEqual([])
    expect(resultEmptyString).toEqual([])
  })
})

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { sortNotesByUpdatedAt } from './path-to-your-module';

describe('sortNotesByUpdatedAt', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path: sorts notes by updatedAt descending', () => {
    const notes = [
      { id: 1, title: 'Note A', updatedAt: 1620000000000 },
      { id: 2, title: 'Note B', updatedAt: 1630000000000 },
      { id: 3, title: 'Note C', updatedAt: 1610000000000 },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    expect(sorted).toEqual([
      { id: 2, title: 'Note B', updatedAt: 1630000000000 },
      { id: 1, title: 'Note A', updatedAt: 1620000000000 },
      { id: 3, title: 'Note C', updatedAt: 1610000000000 },
    ]);
  });

  it('should handle edge case: notes with identical updatedAt retain original order (stable sort)', () => {
    const notes = [
      { id: 1, title: 'First', updatedAt: 1600000000000 },
      { id: 2, title: 'Second', updatedAt: 1600000000000 },
      { id: 3, title: 'Third', updatedAt: 1600000000000 },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    // expect stable sort – original order preserved when timestamps are equal
    expect(sorted).toEqual(notes);
  });

  it('should handle null/empty inputs gracefully', () => {
    // undefined (default parameter)
    expect(sortNotesByUpdatedAt()).toEqual([]);
    // null input
    // @ts-ignore – purposefully passing null to test resilience
    expect(sortNotesByUpdatedAt(null)).toEqual([]);
    // empty array
    expect(sortNotesByUpdatedAt([])).toEqual([]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

/* Assuming the function is exported from 'searchUtil.ts' */
import { matchesSearchQuery } from './searchUtil';

describe('matchesSearchQuery', () => {
  const sampleNote = 'This is a sample note about TypeScript and Vitest testing.';

  it('should handle happy path: query present in note', () => {
    const query = 'vitest';
    const result = matchesSearchQuery(sampleNote, query);
    expect(result).toBeTruthy();
  });

  it('should handle edge case: query present with different case and punctuation', () => {
    const query = 'TESTING.';
    const result = matchesSearchQuery(sampleNote, query);
    expect(result).toBeTruthy();
  });

  it('should handle null/empty: no query or note', () => {
    expect(matchesSearchQuery(null as any, 'test')).toBeFalsy();
    expect(matchesSearchQuery(sampleNote, null as any)).toBeFalsy();
    expect(matchesSearchQuery('', '')).toBeTruthy();
    expect(matchesSearchQuery('', 'test')).toBeFalsy();
    expect(matchesSearchQuery(sampleNote, '')).toBeTruthy();
    expect(matchesSearchQuery(undefined as any, undefined as any)).toBeFalsy();
  });
});

# ── Tests for countWords  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { countWords } from './countWords';

describe('countWords', () => {
  it('should handle happy path. Count words in a normal sentence', () => {
    const text = 'The quick brown fox jumps over the lazy dog';
    const result = countWords(text);
    expect(result).toBe(9);
  });

  it('should handle edge case. Count words with punctuation and multiple spaces', () => {
    const text = 'Hello, world!  This is   a test.';
    const result = countWords(text);
    expect(result).toBe(6);
  });

  it('should handle null/empty. Return 0 for null, undefined, empty string, or 0 passed as number', () => {
    expect(countWords()).toBe(0);
    expect(countWords(null as any)).toBe(0);
    expect(countWords(undefined as any)).toBe(0);
    expect(countWords('')).toBe(0);
    expect(countWords(0 as any)).toBe(0);
  });
});