/**
 * Auto-generated tests for src/hooks/useNotesList.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../useNotesList';



# ── Tests for useNotesList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

describe('useNotesList', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
    vi.clearAllMocks();
  });

  it('should handle happy path - return list of notes', () => {
    const mockNotes = [
      { id: '1', title: 'Note 1', content: 'Content 1' },
      { id: '2', title: 'Note 2', content: 'Content 2' },
    ];

    vi.mock('../api/notes', () => ({
      fetchNotes: vi.fn().mockResolvedValue(mockNotes),
    }));

    const { useNotesList } = require('./useNotesList');
    const { result } = renderHook(() => useNotesList());
    
    expect(result.current.notes).toEqual(mockNotes);
    expect(result.current.isLoading).toBe(false);
    expect(result.current.error).toBeNull();
  });

  it('should handle edge case - single note in list', () => {
    const mockNotes = [{ id: '1', title: 'Single Note', content: 'Only content' }];

    vi.mock('../api/notes', () => ({
      fetchNotes: vi.fn().mockResolvedValue(mockNotes),
    }));

    const { useNotesList } = require('./useNotesList');
    const { result } = renderHook(() => useNotesList());
    
    expect(result.current.notes).toHaveLength(1);
    expect(result.current.notes[0].title).toBe('Single Note');
  });

  it('should handle null/empty - no notes available', () => {
    vi.mock('../api/notes', () => ({
      fetchNotes: vi.fn().mockResolvedValue([]),
    }));

    const { useNotesList } = require('./useNotesList');
    const { result } = renderHook(() => useNotesList());
    
    expect(result.current.notes).toEqual([]);
    expect(result.current.notes.length).toBe(0);
    expect(result.current.isLoading).toBe(false);
  });
});