/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { normalizeTags } from '../src/utils/normalizeTags';

describe('normalizeTags', () => {
  it('should handle happy path with valid tags', () => {
    const input = ['JavaScript', '  TypeScript  ', 'react'];
    const expected = ['javascript', 'typescript', 'react'];
    expect(normalizeTags(input)).toEqual(expected);
  });

  it('should handle edge case with duplicate and whitespace tags', () => {
    const input = ['  Node  ', 'node', '   Express   ', 'express'];
    const expected = ['node', 'express'];
    expect(normalizeTags(input)).toEqual(expected);
  });

  it('should handle null/empty inputs', () => {
    expect(normalizeTags(null)).toEqual([]);
    expect(normalizeTags(undefined)).toEqual([]);
    expect(normalizeTags('')).toEqual([]);
    expect(normalizeTags(0)).toEqual([]);
    expect(normalizeTags()).toEqual([]);
  });
});

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { sortNotesByUpdatedAt } from './sortNotesByUpdatedAt';

describe('sortNotesByUpdatedAt', () => {
  it('should handle happy path with multiple notes', () => {
    const notes = [
      { id: 1, updatedAt: '2023-01-01T10:00:00Z' },
      { id: 2, updatedAt: '2023-01-02T09:00:00Z' },
      { id: 3, updatedAt: '2022-12-31T12:00:00Z' },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    expect(sorted).toEqual([
      { id: 2, updatedAt: '2023-01-02T09:00:00Z' },
      { id: 1, updatedAt: '2023-01-01T10:00:00Z' },
      { id: 3, updatedAt: '2022-12-31T12:00:00Z' },
    ]);
  });

  it('should handle edge case where notes have identical updatedAt values', () => {
    const notes = [
      { id: 'a', updatedAt: '2023-05-01T08:00:00Z' },
      { id: 'b', updatedAt: '2023-05-01T08:00:00Z' },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    // When dates are identical, original order should be preserved (stable sort)
    expect(sorted).toEqual([
      { id: 'a', updatedAt: '2023-05-01T08:00:00Z' },
      { id: 'b', updatedAt: '2023-05-01T08:00:00Z' },
    ]);
  });

  it('should handle null/empty/undefined inputs gracefully', () => {
    // undefined input (function default parameter)
    expect(sortNotesByUpdatedAt()).toEqual([]);

    // null input
    // @ts-expect-error testing runtime handling of null
    expect(sortNotesByUpdatedAt(null)).toEqual([]);

    // empty array
    expect(sortNotesByUpdatedAt([])).toEqual([]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { matchesSearchQuery } from './yourModulePath'; // adjust the import path accordingly

describe('matchesSearchQuery', () => {
  beforeEach(() => {
    // No external dependencies to mock for this pure function
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path where note includes the query (case‑insensitive)', () => {
    const note = { title: 'Meeting Notes', content: 'Discuss project timeline' };
    const query = 'meeting';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  it('should handle edge case with empty query returning true for any note', () => {
    const note = { title: 'Shopping List', content: 'Eggs, Milk, Bread' };
    const query = '';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  it('should handle null/empty inputs gracefully', () => {
    // null note
    expect(matchesSearchQuery(null as any, 'test')).toBe(false);
    // undefined note
    expect(matchesSearchQuery(undefined as any, 'test')).toBe(false);
    // empty string note
    expect(matchesSearchQuery({ title: '', content: '' } as any, 'test')).toBe(false);
    // numeric note (invalid type)
    expect(matchesSearchQuery(0 as any, 'test')).toBe(false);
    // null query
    const validNote = { title: 'Note', content: 'Some content' };
    expect(matchesSearchQuery(validNote, null as any)).toBe(true);
    // undefined query
    expect(matchesSearchQuery(validNote, undefined as any)).toBe(true);
    // empty string query (already covered in edge case, but reaffirm)
    expect(matchesSearchQuery(validNote, '')).toBe(true);
  });
});

# ── Tests for countWords  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assuming the function is exported from a module named './utils'
import { countWords } from './utils';

describe('countWords', () => {
  beforeEach(() => {
    // No external dependencies to mock for this simple utility
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path with a normal sentence', () => {
    const result = countWords('The quick brown fox jumps over the lazy dog');
    expect(result).toBe(9);
  });

  it('should handle edge case with multiple spaces and newlines', () => {
    const result = countWords('Hello   world\n\nThis\tis a test');
    // words: ["Hello","world","This","is","a","test"] => 6
    expect(result).toBe(6);
  });

  it('should handle null/empty inputs gracefully', () => {
    expect(countWords()).toBe(0);
    expect(countWords('')).toBe(0);
    // @ts-ignore: testing runtime behavior with null/undefined
    expect(countWords(null)).toBe(0);
    // @ts-ignore: testing runtime behavior with undefined
    expect(countWords(undefined)).toBe(0);
    expect(countWords(0 as any)).toBe(0);
  });
});