/**
 * Auto-generated tests for src/components/NoteItem.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteItem';



# ── Tests for NoteItem  ──

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import NoteItem from '../src/components/NoteItem';

describe('NoteItem component', () => {
  const mockNote = { id: 1, title: 'Test Note', content: 'Some content' };
  const mockOnSelect = vi.fn();

  it('should handle happy path: renders note title and triggers onSelect when clicked', () => {
    render(<NoteItem note={mockNote} isSelected={false} onSelect={mockOnSelect} />);

    const titleElement = screen.getByText(/Test Note/i);
    expect(titleElement).toBeInTheDocument();

    fireEvent.click(titleElement);
    expect(mockOnSelect).toHaveBeenCalledOnce();
    expect(mockOnSelect).toHaveBeenCalledWith(mockNote.id);
  });

  it('should handle edge case: selected state applies correct class', () => {
    const { rerender } = render(
      <NoteItem note={mockNote} isSelected={false} onSelect={mockOnSelect} />
    );

    const item = screen.getByTestId('note-item');
    expect(item).not.toHaveClass('selected');

    rerender(<NoteItem note={mockNote} isSelected={true} onSelect={mockOnSelect} />);
    expect(item).toHaveClass('selected');
  });

  it('should handle null/empty: accepts undefined note and safely renders', () => {
    const { container } = render(
      <NoteItem note={null as any} isSelected={false} onSelect={mockOnSelect} />
    );

    // Should not crash and render an empty placeholder or fallback
    expect(container.firstChild).toBeNull();
  });
});

# ── Tests for formatDate  ──

import { describe, it, expect } from 'vitest';
import { formatDate } from './yourModulePath';

describe('formatDate', () => {
  it('should handle happy path', () => {
    const isoString = '2023-08-15T12:34:56Z';
    const result = formatDate(isoString);
    expect(typeof result).toBe('string');
    expect(result).toContain('2023');
  });

  it('should handle edge case', () => {
    const isoString = '2020-02-29T00:00:00Z'; // Leap year
    const result = formatDate(isoString);
    expect(typeof result).toBe('string');
    expect(result).toContain('2020');
  });

  it('should handle null/empty', () => {
    expect(formatDate(null as unknown as any)).toBe('');
    expect(formatDate(undefined as any)).toBe('');
    expect(formatDate('')).toBe('');
    expect(formatDate(0 as unknown as any)).toBe('');
  });
});

# ── Tests for truncateContent  ──

import { describe, it, expect } from 'vitest'
import { truncateContent } from './truncateContent'

describe('truncateContent', () => {
  it('should handle happy path', () => {
    const content = 'This is a simple example string that is longer than 80 characters so it should get truncated appropriately.'
    const result = truncateContent(content, 80)
    expect(result.endsWith('...')).toBe(true)
    expect(result.length).toBeLessThanOrEqual(80)
  })

  it('should handle edge case', () => {
    const content = 'Short text'
    const result = truncateContent(content, 80)
    expect(result).toBe(content)
    expect(result.length).toBeLessThanOrEqual(80)
  })

  it('should handle null/empty', () => {
    const resultNull = truncateContent(null as unknown as string)
    const resultUndefined = truncateContent(undefined as unknown as string)
    const resultEmpty = truncateContent('')
    const resultZero = truncateContent('0')
    expect(resultNull).toBe('')
    expect(resultUndefined).toBe('')
    expect(resultEmpty).toBe('')
    expect(resultZero).toBe('0')
  })
})

# ── Tests for handleDelete  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

describe('handleDelete', () => {
  let handleDelete: (e: any) => void
  let mockEvent: { preventDefault: () => void }

  beforeEach(() => {
    // Mock the function under test. In a real scenario this would be an import.
    // For demonstration, we create a simple placeholder that uses e.preventDefault()
    handleDelete = (e: any) => {
      if (e && typeof e.preventDefault === 'function') {
        e.preventDefault()
      }
    }

    mockEvent = { preventDefault: vi.fn() }
  })

  it('should handle happy path', () => {
    // Regular event object with preventDefault method
    handleDelete(mockEvent)
    expect(mockEvent.preventDefault).toHaveBeenCalled()
  })

  it('should handle edge case', () => {
    // Event object that does not have preventDefault but still processes
    const edgeEvent = {}
    handleDelete(edgeEvent as any) // should not throw
    // No preventDefault to call, but test that no error occurs
    expect(() => handleDelete(edgeEvent as any)).not.toThrow()
  })

  it('should handle null/empty', () => {
    // Null event
    expect(() => handleDelete(null)).not.toThrow()
    // Undefined event
    expect(() => handleDelete(undefined)).not.toThrow()
    // Empty string event
    expect(() => handleDelete('')).not.toThrow()
    // Zero event
    expect(() => handleDelete(0)).not.toThrow()
  })
})