/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteList';



# ── Tests for NoteList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import NoteList from './NoteList';

describe('NoteList component', () => {
  let onSelectNote: vi.Mock;

  beforeEach(() => {
    onSelectNote = vi.fn();
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path - renders notes and selects one', () => {
    const notes = [
      { id: 1, title: 'Note 1' },
      { id: 2, title: 'Note 2' },
    ];

    vi.mock('./useNotes', () => ({
      useNotes: () => notes,
    }));

    const { default: useNotes } = await import('./useNotes');
    vi.spyOn(useNotes, 'useNotes').mockReturnValue(notes);

    render(
      <NoteList onSelectNote={onSelectNote} selectedNoteId={null} />
    );

    expect(screen.getByText('Note 1')).toBeInTheDocument();
    expect(screen.getByText('Note 2')).toBeInTheDocument();

    fireEvent.click(screen.getByText('Note 2'));
    expect(onSelectNote).toHaveBeenCalledWith(2);
  });

  it('should handle edge case - selectedNoteId is present', () => {
    const notes = [
      { id: 1, title: 'Note A' },
      { id: 2, title: 'Note B' },
    ];

    vi.mock('./useNotes', () => ({
      useNotes: () => notes,
    }));

    const { default: useNotes } = await import('./useNotes');
    vi.spyOn(useNotes, 'useNotes').mockReturnValue(notes);

    render(
      <NoteList onSelectNote={onSelectNote} selectedNoteId={1} />
    );

    const activeItem = screen.getByRole('button', { name: /Note A/i });
    expect(activeItem).toHaveClass('selected');
    expect(screen.getByRole('button', { name: /Note B/i })).not.toHaveClass('selected');
  });

  it('should handle null/empty props - renders nothing or fallback', () => {
    vi.mock('./useNotes', () => ({
      useNotes: () => [],
    }));

    const { default: useNotes } = await import('./useNotes');
    vi.spyOn(useNotes, 'useNotes').mockReturnValue([]);

    const { container } = render(
      <NoteList onSelectNote={onSelectNote} selectedNoteId={undefined} />
    );

    expect(container).toBeEmptyDOMElement();
  });
});