/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteList';



# ── Tests for NoteList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup } from '@testing-library/react';
import '@testing-library/jest-dom';
import NoteList from '@/components/NoteList';

describe('NoteList component', () => {
  const mockOnSelectNote = vi.fn();

  beforeEach(() => {
    mockOnSelectNote.mockReset();
  });

  afterEach(() => {
    cleanup();
  });

  it('should handle happy path - renders notes and calls onSelectNote with correct id', () => {
    const notes = [
      { id: '1', title: 'Note 1' },
      { id: '2', title: 'Note 2' },
    ];
    render(
      <NoteList
        notes={notes}
        selectedNoteId="1"
        onSelectNote={mockOnSelectNote}
      />
    );

    // Verify that both notes are rendered
    expect(screen.getByText('Note 1')).toBeInTheDocument();
    expect(screen.getByText('Note 2')).toBeInTheDocument();

    // Click the second note
    fireEvent.click(screen.getByText('Note 2'));
    expect(mockOnSelectNote).toHaveBeenCalledOnce();
    expect(mockOnSelectNote).toHaveBeenCalledWith('2');
  });

  it('should handle edge case - renders with empty notes array without crashing', () => {
    render(
      <NoteList
        notes={[]}
        selectedNoteId={null}
        onSelectNote={mockOnSelectNote}
      />
    );

    // Expect a placeholder or nothing rendered
    const list = screen.queryByRole('list');
    expect(list).toBeInTheDocument();
    expect(list?.children.length).toBe(0);
    // No callback should be called
    expect(mockOnSelectNote).not.toHaveBeenCalled();
  });

  it('should handle null/empty inputs - gracefully handles undefined props', () => {
    // @ts-expect-error testing undefined props
    render(<NoteList onSelectNote={undefined} selectedNoteId={undefined} />);

    // Component should render without throwing
    const container = screen.getByTestId('note-list-container');
    expect(container).toBeInTheDocument();

    // No interaction possible, ensure no errors
    expect(mockOnSelectNote).not.toHaveBeenCalled();
  });
});