/**
 * Auto-generated tests for src/components/NoteItem.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteItem';



# ── Tests for NoteItem  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import React from 'react';
import NoteItem from './NoteItem';

describe('NoteItem component', () => {
  const mockOnSelect = vi.fn();

  beforeEach(() => {
    mockOnSelect.mockReset();
  });

  it('should handle happy path: renders note text and triggers onSelect when clicked', () => {
    const note = { id: 1, text: 'Test note' };
    render(<NoteItem note={note} isSelected={false} onSelect={mockOnSelect} />);

    // note text should be in the document
    expect(screen.getByText('Test note')).toBeInTheDocument();

    // clicking the root element should call onSelect with note id
    fireEvent.click(screen.getByRole('button'));
    expect(mockOnSelect).toHaveBeenCalledOnce();
    expect(mockOnSelect).toHaveBeenCalledWith(note.id);
  });

  it('should handle edge case: renders correctly when isSelected is true', () => {
    const note = { id: 2, text: 'Edge case note' };
    const { container } = render(
      <NoteItem note={note} isSelected={true} onSelect={mockOnSelect} />
    );

    // component may apply a selected class; check for it
    const root = container.firstChild as HTMLElement;
    expect(root).toHaveClass('selected');

    // still displays the note text
    expect(screen.getByText('Edge case note')).toBeInTheDocument();
  });

  it('should handle null/empty inputs gracefully', () => {
    // Render with null note (should not crash)
    // Using a fallback note to avoid TypeScript errors
    // @ts-ignore
    render(<NoteItem note={null} isSelected={false} onSelect={mockOnSelect} />);
    // Should render nothing or a placeholder
    expect(screen.queryByRole('button')).toBeNull();

    // Render with empty string note text
    const emptyNote = { id: 3, text: '' };
    render(<NoteItem note={emptyNote} isSelected={false} onSelect={mockOnSelect} />);
    // Empty string should not produce visible text
    expect(screen.queryByText('')).toBeNull();

    // Render with undefined onSelect (should not throw)
    const note = { id: 4, text: 'No handler' };
    // @ts-ignore
    render(<NoteItem note={note} isSelected={false} onSelect={undefined} />);
    // clicking should not throw
    expect(() => fireEvent.click(screen.getByRole('button'))).not.toThrow();
  });
});

# ── Tests for formatDate  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { formatDate } from './formatDate';

describe('formatDate', () => {
  beforeEach(() => {
    // No external dependencies to mock for this pure function
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path with standard ISO datetime string', () => {
    const iso = '2023-08-15T13:45:30Z';
    // Expected format: e.g., "08/15/2023, 13:45"
    const result = formatDate(iso);
    expect(result).toBe('08/15/2023, 13:45');
  });

  it('should handle edge case with date only ISO string', () => {
    const iso = '2023-12-01';
    const result = formatDate(iso);
    // Assuming time defaults to 00:00
    expect(result).toBe('12/01/2023, 00:00');
  });

  it('should handle null/empty inputs gracefully', () => {
    expect(formatDate(null as any)).toBe('');
    expect(formatDate(undefined as any)).toBe('');
    expect(formatDate('')).toBe('');
    expect(formatDate(0 as any)).toBe('');
  });
});

# ── Tests for truncateContent  ──

import { describe, it, expect } from 'vitest'

describe('truncateContent', () => {
  // Import the function (assuming it is exported from a module named './truncate')
  const { truncateContent } = await import('./truncate')

  it('should handle happy path', () => {
    const content = 'This is a short content that is less than maxLength.'
    const result = truncateContent(content, 50)
    expect(result).toBe(content)
  })

  it('should handle edge case', () => {
    const content = 'BoundaryCheck'
    const maxLength = content.length
    const result = truncateContent(content, maxLength)
    expect(result).toBe(content)
  })

  it('should handle null/empty', () => {
    const content = ''
    const result = truncateContent(content, 80)
    expect(result).toBe('')
  })
})

# ── Tests for handleDelete  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assuming the function is exported from a module named './handleDelete'
import { handleDelete } from './handleDelete';

describe('handleDelete', () => {
  let mockEvent: {
    preventDefault: ReturnType<typeof vi.fn>;
    stopPropagation: ReturnType<typeof vi.fn>;
    target: { closest: ReturnType<typeof vi.fn> };
  };

  beforeEach(() => {
    mockEvent = {
      preventDefault: vi.fn(),
      stopPropagation: vi.fn(),
      target: {
        // Simulate finding the closest deletable element (e.g., a button's parent)
        closest: vi.fn(),
      },
    };
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path by preventing default and removing the element', () => {
    const mockElement = { remove: vi.fn() };
    // closest should return the element to be removed
    mockEvent.target.closest.mockReturnValue(mockElement as any);

    handleDelete(mockEvent as any);

    expect(mockEvent.preventDefault).toHaveBeenCalledOnce();
    expect(mockEvent.stopPropagation).toHaveBeenCalledOnce();
    expect(mockEvent.target.closest).toHaveBeenCalledWith('.deletable'); // assumed selector
    expect(mockElement.remove).toHaveBeenCalledOnce();
  });

  it('should handle edge case where closest returns null (no element to delete)', () => {
    mockEvent.target.closest.mockReturnValue(null);

    handleDelete(mockEvent as any);

    expect(mockEvent.preventDefault).toHaveBeenCalledOnce();
    expect(mockEvent.stopPropagation).toHaveBeenCalledOnce();
    // Should not attempt to call remove on a null element
    // No error should be thrown; simply exit gracefully
  });

  it('should handle null/empty input without throwing', () => {
    // Test with undefined
    expect(() => handleDelete(undefined as any)).not.toThrow();

    // Test with null
    expect(() => handleDelete(null as any)).not.toThrow();

    // Test with empty object (missing properties)
    expect(() => handleDelete({} as any)).not.toThrow();

    // Test with numeric zero
    expect(() => handleDelete(0 as any)).not.toThrow();
  });
});