/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { normalizeTags } from './normalizeTags';

describe('normalizeTags', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path: normal tags without duplicates or spaces', () => {
    const input = ['JavaScript', 'Testing', 'Vitest'];
    const result = normalizeTags(input);
    expect(result).toEqual(['javascript', 'testing', 'vitest']);
  });

  it('should handle edge case: tags with mixed cases, spaces, and duplicates', () => {
    const input = ['  Node.js  ', 'node.js', 'API', 'api ', '   '];
    const result = normalizeTags(input);
    expect(result).toEqual(['node.js', 'api']);
  });

  it('should handle null/empty: null, undefined, empty string, 0', () => {
    expect(normalizeTags(null as any)).toEqual([]);
    expect(normalizeTags(undefined as any)).toEqual([]);
    expect(normalizeTags(['', '   ', 0] as any)).toEqual([]);
    expect(normalizeTags([])).toEqual([]);
  });
});

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assume the function is exported from './notesUtils'
import { sortNotesByUpdatedAt } from './notesUtils';

describe('sortNotesByUpdatedAt', () => {
  // Happy path test - notes with different timestamps
  it('should handle happy path: return notes sorted by updatedAt descending', () => {
    const notes = [
      { id: 1, title: 'A', updatedAt: new Date('2023-01-01') },
      { id: 2, title: 'B', updatedAt: new Date('2023-03-01') },
      { id: 3, title: 'C', updatedAt: new Date('2023-02-01') },
    ];

    const sorted = sortNotesByUpdatedAt(notes);

    expect(sorted).toEqual([
      { id: 2, title: 'B', updatedAt: new Date('2023-03-01') },
      { id: 3, title: 'C', updatedAt: new Date('2023-02-01') },
      { id: 1, title: 'A', updatedAt: new Date('2023-01-01') },
    ]);
  });

  // Edge case test - notes with identical timestamps
  it('should handle edge case: notes with equal updatedAt keep original order', () => {
    const equalTime = new Date('2023-05-01');
    const notes = [
      { id: 1, title: 'X', updatedAt: equalTime },
      { id: 2, title: 'Y', updatedAt: equalTime },
      { id: 3, title: 'Z', updatedAt: equalTime },
    ];

    const sorted = sortNotesByUpdatedAt(notes);

    // Should preserve original order when timestamps are equal
    expect(sorted).toEqual(notes);
  });

  // Null/empty test - handling null, undefined, empty array and falsy values
  it('should handle null/empty inputs gracefully', () => {
    expect(sortNotesByUpdatedAt(null)).toEqual([]);
    expect(sortNotesByUpdatedAt(undefined)).toEqual([]);
    expect(sortNotesByUpdatedAt([])).toEqual([]);

    // If a note missing updatedAt is passed, it should be treated as minimal date
    const notes = [
      { id: 1, title: 'No date' },
      { id: 2, title: 'With date', updatedAt: new Date('2023-04-01') },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    expect(sorted).toEqual([
      { id: 2, title: 'With date', updatedAt: new Date('2023-04-01') },
      { id: 1, title: 'No date' },
    ]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { matchesSearchQuery } from '../src/utils'; // adjust the import path as needed

describe('matchesSearchQuery', () => {
  beforeEach(() => {
    // No external modules to mock for this pure utility function
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path where note contains the query (case‑insensitive)', () => {
    const note = 'Learn Vitest testing framework';
    const query = 'vitest';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  it('should handle edge case with empty query string returning true for any note', () => {
    const note = 'Any note content';
    const query = '';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  it('should handle null/empty inputs gracefully', () => {
    // note is null
    expect(matchesSearchQuery(null as any, 'test')).toBe(false);
    // query is null
    expect(matchesSearchQuery('some note', null as any)).toBe(false);
    // both are undefined
    expect(matchesSearchQuery(undefined as any, undefined as any)).toBe(false);
    // note is empty string
    expect(matchesSearchQuery('', 'test')).toBe(false);
    // query is 0 (numeric falsy value)
    expect(matchesSearchQuery('some note', 0 as any)).toBe(false);
  });
});

# ── Tests for countWords  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { countWords } from './path/to/module';

describe('countWords', () => {
  it('should handle happy path with normal sentence', () => {
    const text = 'Hello world, this is a test.';
    // Expected word count: 6 (splitting on whitespace, ignoring punctuation)
    expect(countWords(text)).toBe(6);
  });

  it('should handle edge case with multiple spaces and newline characters', () => {
    const text = '  Multiple   spaces\nand\t tabs  ';
    // Words are: ['Multiple', 'spaces', 'and', 'tabs'] => 4
    expect(countWords(text)).toBe(4);
  });

  it('should handle null/empty inputs gracefully', () => {
    // undefined input (function default parameter)
    expect(countWords()).toBe(0);
    // null input
    // @ts-ignore: testing runtime behavior with null
    expect(countWords(null)).toBe(0);
    // empty string
    expect(countWords('')).toBe(0);
    // numeric zero converted to string
    // @ts-ignore: testing non-string input
    expect(countWords(0)).toBe(0);
  });
});