/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteList';



# ── Tests for NoteList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup } from '@testing-library/react';
import NoteList from '@/components/NoteList';

describe('NoteList Component', () => {
  const onSelectNoteMock = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    cleanup();
  });

  it('should handle happy path by rendering notes and invoking onSelectNote when a note is clicked', () => {
    const notes = [
      { id: '1', title: 'First Note' },
      { id: '2', title: 'Second Note' },
    ];
    render(<NoteList notes={notes} onSelectNote={onSelectNoteMock} selectedNoteId="1" />);

    // Verify both notes are rendered
    expect(screen.getByText('First Note')).toBeInTheDocument();
    expect(screen.getByText('Second Note')).toBeInTheDocument();

    // Click the second note
    fireEvent.click(screen.getByText('Second Note'));

    // onSelectNote should be called with the clicked note's id
    expect(onSelectNoteMock).toHaveBeenCalledOnce();
    expect(onSelectNoteMock).toHaveBeenCalledWith('2');
  });

  it('should handle edge case where notes array is empty but component renders without crashing', () => {
    const notes: Array<{ id: string; title: string }> = [];
    render(<NoteList notes={notes} onSelectNote={onSelectNoteMock} selectedNoteId={null} />);

    // Expect no note items to be rendered
    const noteItems = screen.queryAllByRole('listitem');
    expect(noteItems).toHaveLength(0);

    // Component should still display a placeholder message
    expect(screen.getByText(/no notes/i)).toBeInTheDocument();
  });

  it('should handle null/empty props gracefully without throwing errors', () => {
    // Render with undefined notes and missing selectedNoteId
    // @ts-expect-error testing runtime behaviour with invalid props
    render(<NoteList onSelectNote={onSelectNoteMock} />);

    // The component should render a fallback UI rather than crashing
    expect(screen.getByText(/no notes/i)).toBeInTheDocument();

    // Calling onSelectNote should still be safe (no notes to click)
    expect(onSelectNoteMock).not.toHaveBeenCalled();
  });
});