/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteList';



# ── Tests for NoteList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup } from '@testing-library/react';
import React from 'react';
import NoteList from '@/components/NoteList';

// No external module dependencies to mock for this component
vi.mock('', () => ({}));

describe('NoteList component', () => {
  afterEach(() => {
    cleanup();
  });

  it('should handle happy path: renders notes and calls onSelectNote when a note is clicked', () => {
    const mockOnSelect = vi.fn();
    const notes = [
      { id: '1', title: 'First Note' },
      { id: '2', title: 'Second Note' },
    ];
    render(
      <NoteList
        onSelectNote={mockOnSelect}
        selectedNoteId="1"
        notes={notes}
      />
    );

    // Verify that both notes are rendered
    expect(screen.getByText('First Note')).toBeInTheDocument();
    expect(screen.getByText('Second Note')).toBeInTheDocument();

    // Click the second note and ensure callback is invoked with correct id
    fireEvent.click(screen.getByText('Second Note'));
    expect(mockOnSelect).toHaveBeenCalledOnce();
    expect(mockOnSelect).toHaveBeenCalledWith('2');
  });

  it('should handle edge case: renders correctly when selectedNoteId does not match any note', () => {
    const mockOnSelect = vi.fn();
    const notes = [{ id: '1', title: 'Only Note' }];
    render(
      <NoteList
        onSelectNote={mockOnSelect}
        selectedNoteId="non-existent"
        notes={notes}
      />
    );

    // The note should still be rendered and not be highlighted as selected
    const noteElement = screen.getByText('Only Note');
    expect(noteElement).toBeInTheDocument();
    expect(noteElement).not.toHaveClass('selected'); // assuming selected class usage
  });

  it('should handle null/empty props without crashing', () => {
    const mockOnSelect = vi.fn();
    render(
      <NoteList
        onSelectNote={mockOnSelect}
        selectedNoteId={null}
        notes={[]}
      />
    );

    // With no notes, component should render nothing or a placeholder
    expect(screen.queryByRole('listitem')).toBeNull();

    // Ensure the onSelectNote callback is still a function and not called
    expect(mockOnSelect).not.toHaveBeenCalled();
  });
});