/**
 * Auto-generated tests for src/hooks/useNotesList.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../useNotesList';



# ── Tests for useNotesList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

vi.mock('../api/notes', () => ({
  fetchNotes: vi.fn(),
  deleteNote: vi.fn(),
}));

vi.mock('../stores/notesStore', () => ({
  useNotesStore: vi.fn(() => ({
    notes: [],
    setNotes: vi.fn(),
  })),
}));

import { fetchNotes, deleteNote } from '../api/notes';
import { useNotesStore } from '../stores/notesStore';

const mockFetchNotes = fetchNotes as ReturnType<typeof vi.fn>;
const mockDeleteNote = deleteNote as ReturnType<typeof vi.fn>;
const mockUseNotesStore = useNotesStore as ReturnType<typeof vi.fn>;

describe('useNotesList', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.resetAllMocks();
  });

  it('should handle happy path with valid notes data', () => {
    const mockNotes = [
      { id: '1', title: 'Note 1', content: 'Content 1', createdAt: '2024-01-01' },
      { id: '2', title: 'Note 2', content: 'Content 2', createdAt: '2024-01-02' },
    ];

    mockFetchNotes.mockResolvedValue(mockNotes);
    mockUseNotesStore.mockReturnValue({
      notes: mockNotes,
      setNotes: vi.fn(),
    });

    const result = mockFetchNotes();
    
    expect(result).resolves.toEqual(mockNotes);
    expect(mockFetchNotes).toHaveBeenCalledTimes(1);
  });

  it('should handle edge case with single note', async () => {
    const singleNote = [{ id: '1', title: 'Single Note', content: 'Only note', createdAt: '2024-01-01' }];

    mockFetchNotes.mockResolvedValue(singleNote);
    mockUseNotesStore.mockReturnValue({
      notes: singleNote,
      setNotes: vi.fn(),
    });

    const result = await mockFetchNotes();
    
    expect(result).toHaveLength(1);
    expect(result[0].title).toBe('Single Note');
  });

  it('should handle null/empty notes list', async () => {
    mockFetchNotes.mockResolvedValue([]);
    mockUseNotesStore.mockReturnValue({
      notes: [],
      setNotes: vi.fn(),
    });

    const result = await mockFetchNotes();
    
    expect(result).toEqual([]);
    expect(result).toHaveLength(0);
  });
});