/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteList';



// ── Tests for NoteList  ──

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import NoteList from './NoteList';

describe('NoteList', () => {
  const notes = [
    { id: '1', title: 'First note' },
    { id: '2', title: 'Second note' },
  ];

  it('should handle happy path: renders notes and calls onSelectNote when a note is clicked', () => {
    const onSelectNote = vi.fn();
    render(<NoteList onSelectNote={onSelectNote} selectedNoteId={null} notes={notes} />);
    // Verify notes are rendered
    expect(screen.getByText('First note')).toBeInTheDocument();
    expect(screen.getByText('Second note')).toBeInTheDocument();

    // Click the first note
    fireEvent.click(screen.getByText('First note'));
    expect(onSelectNote).toHaveBeenCalledOnce();
    expect(onSelectNote).toHaveBeenCalledWith('1');
  });

  it('should handle edge case: highlights the selected note correctly', () => {
    const onSelectNote = vi.fn();
    render(<NoteList onSelectNote={onSelectNote} selectedNoteId="2" notes={notes} />);
    const selected = screen.getByText('Second note');
    // Assuming the selected note gets a specific class, e.g., 'selected'
    expect(selected).toHaveClass('selected');
    // The other note should not have the selected class
    expect(screen.getByText('First note')).not.toHaveClass('selected');
  });

  it('should handle null/empty inputs gracefully', () => {
    const onSelectNote = vi.fn();
    // Render with empty notes array
    render(<NoteList onSelectNote={onSelectNote} selectedNoteId={null} notes={[]} />);
    // Expect no note items to be rendered
    expect(screen.queryAllByRole('listitem')).toHaveLength(0);
    // Render with undefined notes prop (fallback to empty list)
    // @ts-ignore – testing undefined prop handling
    render(<NoteList onSelectNote={onSelectNote} selectedNoteId={null} />);
    expect(screen.queryAllByRole('listitem')).toHaveLength(0);
  });
});