/**
 * Auto-generated tests for src/components/NoteItem.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteItem';



# ── Tests for NoteItem  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import NoteItem from './NoteItem';

describe('NoteItem component', () => {
  const note = { id: '1', title: 'Sample Note', content: 'Hello World' };
  let onSelect: vi.Mock;

  beforeEach(() => {
    onSelect = vi.fn();
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path', () => {
    render(<NoteItem note={note} isSelected={false} onSelect={onSelect} />);
    const titleElement = screen.getByText(note.title);
    const contentElement = screen.getByText(note.content);
    expect(titleElement).toBeInTheDocument();
    expect(contentElement).toBeInTheDocument();

    const container = screen.getByRole('button');
    fireEvent.click(container);
    expect(onSelect).toHaveBeenCalledWith(note.id);
  });

  it('should handle edge case when isSelected is true', () => {
    render(<NoteItem note={note} isSelected={true} onSelect={onSelect} />);
    const container = screen.getByRole('button');
    expect(container).toHaveClass('selected');
  });

  it('should handle null/empty props', () => {
    render(<NoteItem note={null as any} isSelected={undefined as any} onSelect={onSelect} />);
    const placeholder = screen.getByText(/no note/i);
    expect(placeholder).toBeInTheDocument();
  });
});

# ── Tests for formatDate  ──

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';

// Assuming the function is exported from the same module
import { formatDate } from './formatDate';

describe('formatDate', () => {
  // 1. Happy path
  it('should handle happy path with a valid ISO string', () => {
    const isoString = '2023-08-15T14:30:00Z';
    const result = formatDate(isoString);
    expect(result).toBeTypeOf('string');
    // Basic check that it contains the year, month, day
    expect(result).toMatch(/2023-08-15/);
  });

  // 2. Edge case
  it('should handle edge case of a leap day ISO string', () => {
    const isoString = '2020-02-29T00:00:00Z';
    const result = formatDate(isoString);
    expect(result).toBeTypeOf('string');
    expect(result).toMatch(/2020-02-29/);
  });

  // 3. Null / Empty inputs
  it('should handle null, undefined, empty string, and zero inputs', () => {
    const inputs = [null, undefined, '', 0];
    inputs.forEach((input) => {
      const result = formatDate(input as any);
      // Assuming formatDate returns null or undefined for invalid inputs
      expect(result).toBeNull();
    });
  });
});

# ── Tests for truncateContent  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { truncateContent } from './truncateContent';

describe('truncateContent', () => {
  it('should handle happy path with content shorter than maxLength', () => {
    const content = 'Hello, world!';
    const result = truncateContent(content, 80);
    expect(result).toBe(content);
  });

  it('should handle edge case when content length is exactly maxLength', () => {
    const content = 'a'.repeat(80);
    const result = truncateContent(content, 80);
    expect(result).toBe(content);
  });

  it('should handle null/empty inputs', () => {
    const resultNull = truncateContent(null as any, 80);
    const resultUndefined = truncateContent(undefined as any, 80);
    const resultEmptyString = truncateContent('', 80);
    const resultZeroLength = truncateContent('non-empty', 0);

    expect(resultNull).toBe('');
    expect(resultUndefined).toBe('');
    expect(resultEmptyString).toBe('');
    expect(resultZeroLength).toBe('');
  });
});

# ── Tests for handleDelete  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assume the delete service and navigation are imported in the module
import * as api from './api';
import * as router from './router';
import { handleDelete } from './handler';

vi.mock('./api');
vi.mock('./router');

describe('handleDelete', () => {
  const mockEvent = { preventDefault: vi.fn() } as unknown as Event;

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path when delete succeeds', async () => {
    // Arrange
    const deleteResp = Promise.resolve({ success: true });
    (api.deleteNote as vi.Mock).mockResolvedValue(deleteResp);
    (router.navigate as vi.Mock).mockImplementation(() => {});

    // Act
    await handleDelete(mockEvent);

    // Assert
    expect(mockEvent.preventDefault).toHaveBeenCalled();
    expect(api.deleteNote).toHaveBeenCalled();
    expect(router.navigate).toHaveBeenCalledWith('/notes');
  });

  it('should handle edge case when delete returns an error object', async () => {
    // Arrange
    const errorResp = Promise.resolve({ success: false, message: 'Not found' });
    (api.deleteNote as vi.Mock).mockResolvedValue(errorResp);

    // Act
    await handleDelete(mockEvent);

    // Assert
    expect(mockEvent.preventDefault).toHaveBeenCalled();
    expect(api.deleteNote).toHaveBeenCalled();
    // Depending on implementation, you might check for an error handling call
    // Here we just ensure no navigation occurs
    expect(router.navigate).not.toHaveBeenCalled();
  });

  it('should handle null/empty event when event is null', async () => {
    // Act
    await handleDelete(null as unknown as Event);

    // Assert
    // No operations should throw; ensure mocks were not called
    expect(api.deleteNote).not.toHaveBeenCalled();
    expect(router.navigate).not.toHaveBeenCalled();
  });
});