/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assuming the normalizeTags function is exported from './tags'
import { normalizeTags } from './tags';

describe('normalizeTags', () => {
  it('should handle happy path', () => {
    const input = ['  Tag One ', 'tagTwo', ' TAG Three  '];
    const result = normalizeTags(input);
    expect(result).toEqual(['tag-one', 'tagtwo', 'tag-three']);
  });

  it('should handle edge case', () => {
    // edge case: duplicate entries and mixed case
    const input = ['Tag', 'tag', 'TAG', 'Another', 'another'];
    const result = normalizeTags(input);
    // expecting deduplication and normalization
    expect(result).toEqual(['tag', 'another']);
  });

  it('should handle null/empty', () => {
    // passing undefined, null and empty array
    const resultFromUndefined = normalizeTags(undefined as any);
    const resultFromNull = normalizeTags(null as any);
    const resultFromEmpty = normalizeTags([]);
    expect(resultFromUndefined).toEqual([]);
    expect(resultFromNull).toEqual([]);
    expect(resultFromEmpty).toEqual([]);
  });
});

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { sortNotesByUpdatedAt } from './utils';

describe('sortNotesByUpdatedAt', () => {
  it('should handle happy path with mixed dates', () => {
    const notes = [
      { id: 1, updatedAt: '2023-01-02T10:00:00Z' },
      { id: 2, updatedAt: '2023-04-15T12:30:00Z' },
      { id: 3, updatedAt: '2022-12-25T08:45:00Z' },
    ];
    const result = sortNotesByUpdatedAt(notes);
    expect(result).toEqual([
      { id: 2, updatedAt: '2023-04-15T12:30:00Z' },
      { id: 1, updatedAt: '2023-01-02T10:00:00Z' },
      { id: 3, updatedAt: '2022-12-25T08:45:00Z' },
    ]);
  });

  it('should handle edge case with identical timestamps', () => {
    const notes = [
      { id: 1, updatedAt: '2023-05-01T00:00:00Z' },
      { id: 2, updatedAt: '2023-05-01T00:00:00Z' },
      { id: 3, updatedAt: '2023-04-30T23:59:59Z' },
    ];
    const result = sortNotesByUpdatedAt(notes);
    // When timestamps are equal, original order should be preserved (stable sort)
    expect(result).toEqual([
      { id: 1, updatedAt: '2023-05-01T00:00:00Z' },
      { id: 2, updatedAt: '2023-05-01T00:00:00Z' },
      { id: 3, updatedAt: '2023-04-30T23:59:59Z' },
    ]);
  });

  it('should handle null/empty inputs gracefully', () => {
    // @ts-ignore – testing runtime behavior with null
    expect(sortNotesByUpdatedAt(null)).toEqual([]);
    // @ts-ignore – testing runtime behavior with undefined
    expect(sortNotesByUpdatedAt(undefined)).toEqual([]);
    expect(sortNotesByUpdatedAt([])).toEqual([]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assuming matchesSearchQuery is exported from the module under test
import { matchesSearchQuery } from './matchesSearchQuery';

describe('matchesSearchQuery', () => {
  // Happy path: typical usage with matching substring
  it('should handle happy path with matching query', () => {
    const note = 'Remember to buy milk and eggs';
    const query = 'milk';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  // Edge case: empty query should match any note (or be considered true)
  it('should handle edge case with empty query', () => {
    const note = 'Any content here';
    const query = '';
    const result = matchesSearchQuery(note, query);
    // Assuming empty query returns true for any note
    expect(result).toBe(true);
  });

  // Null/empty inputs: note is null/undefined and query is null/undefined/empty
  it('should handle null/empty inputs gracefully', () => {
    // @ts-ignore – intentionally passing invalid types
    const result1 = matchesSearchQuery(null, 'test');
    // @ts-ignore – intentionally passing invalid types
    const result2 = matchesSearchQuery(undefined, 'test');
    // @ts-ignore – intentionally passing invalid types
    const result3 = matchesSearchQuery('', null);
    // @ts-ignore – intentionally passing invalid types
    const result4 = matchesSearchQuery('', undefined);
    // @ts-ignore – intentionally passing invalid types
    const result5 = matchesSearchQuery('', '');

    // Expected behavior: non‑string notes or queries should result in false
    expect(result1).toBe(false);
    expect(result2).toBe(false);
    expect(result3).toBe(false);
    expect(result4).toBe(false);
    expect(result5).toBe(true); // empty note with empty query considered a match
  });
});

# ── Tests for countWords  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { countWords } from './path/to/module';

describe('countWords', () => {
  it('should handle happy path with regular sentence', () => {
    const text = 'The quick brown fox jumps over the lazy dog';
    const result = countWords(text);
    expect(result).toBe(9);
  });

  it('should handle edge case with multiple spaces and newline characters', () => {
    const text = '  Hello   world\nThis\tis a test  ';
    const result = countWords(text);
    // Expected words: ["Hello","world","This","is","a","test"] => 6
    expect(result).toBe(6);
  });

  it('should handle null/empty/undefined inputs gracefully', () => {
    // Empty string
    expect(countWords('')).toBe(0);
    // Null
    // @ts-ignore testing runtime behavior with null
    expect(countWords(null)).toBe(0);
    // Undefined (default parameter)
    expect(countWords(undefined)).toBe(0);
    // Zero (should be treated as string "0")
    expect(countWords(0 as any)).toBe(1);
  });
});