/**
 * Auto-generated tests for src/components/NoteItem.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteItem';



# ── Tests for NoteItem  ──

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import NoteItem from './NoteItem';

// Mock the CSS module or any other dependencies if they exist
vi.mock('./NoteItem.module.css', () => ({
  default: {},
}));

describe('NoteItem Component', () => {
  const mockOnSelect = vi.fn();

  beforeEach(() => {
    mockOnSelect.mockReset();
  });

  it('should handle happy path – renders note and triggers onSelect on click', () => {
    const note = { id: 1, title: 'Test Note', content: 'Hello world' };
    const { getByText, container } = render(
      <NoteItem note={note} isSelected={false} onSelect={mockOnSelect} />
    );

    // note title should be rendered
    expect(getByText('Test Note')).toBeInTheDocument();
    // note content should be rendered
    expect(getByText('Hello world')).toBeInTheDocument();

    // clicking the root element should call onSelect with note id
    fireEvent.click(container.firstChild as HTMLElement);
    expect(mockOnSelect).toHaveBeenCalledOnce();
    expect(mockOnSelect).toHaveBeenCalledWith(note.id);
  });

  it('should handle edge case – renders correctly when selected', () => {
    const note = { id: 2, title: 'Edge Note', content: 'Edge content' };
    const { container } = render(
      <NoteItem note={note} isSelected={true} onSelect={mockOnSelect} />
    );

    // Assuming a selected note gets a special CSS class 'selected'
    expect(container.firstChild).toHaveClass('selected');
  });

  it('should handle null/empty – renders fallback UI and does not crash', () => {
    const note = { id: 3, title: '', content: '' };
    const { queryByText, container } = render(
      <NoteItem note={note} isSelected={false} onSelect={mockOnSelect} />
    );

    // No title or content should be rendered
    expect(queryByText('')).not.toBeInTheDocument();

    // Clicking should still call onSelect with the note id
    fireEvent.click(container.firstChild as HTMLElement);
    expect(mockOnSelect).toHaveBeenCalledOnce();
    expect(mockOnSelect).toHaveBeenCalledWith(note.id);
  });
});

# ── Tests for formatDate  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { formatDate } from './dateUtils'; // adjust import path as needed

describe('formatDate', () => {
  it('should handle happy path with a valid ISO string', () => {
    const isoString = '2023-08-15T13:45:30Z';
    const result = formatDate(isoString);
    // Expected format: DD MMM YYYY (e.g., "15 Aug 2023")
    const regex = /^\d{2} \w{3} \d{4}$/;
    expect(result).toMatch(regex);
  });

  it('should handle edge case with year boundary and midnight UTC', () => {
    const isoString = '1900-01-01T00:00:00Z';
    const result = formatDate(isoString);
    const regex = /^\d{2} \w{3} \d{4}$/;
    expect(result).toMatch(regex);
  });

  it('should handle null/empty inputs gracefully', () => {
    // Test with undefined, null, empty string, and numeric zero
    const inputs: any[] = [undefined, null, '', 0];
    inputs.forEach((input) => {
      const result = formatDate(input);
      // Expecting either an empty string or a specific fallback value
      expect(typeof result).toBe('string');
      expect(result).toMatch(/^(?:|<no date>)/);
    });
  });
});

# ── Tests for truncateContent  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { truncateContent } from './truncateContent';

describe('truncateContent', () => {
  beforeEach(() => {
    // no external dependencies to mock
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path with default maxLength', () => {
    const content = 'a'.repeat(100);
    const result = truncateContent(content);
    expect(result.length).toBe(80);
    expect(result).toBe('a'.repeat(80));
  });

  it('should handle edge case when content length equals maxLength', () => {
    const content = 'b'.repeat(50);
    const result = truncateContent(content, 50);
    expect(result.length).toBe(50);
    expect(result).toBe(content);
  });

  it('should handle null/empty inputs gracefully', () => {
    expect(truncateContent(null as any)).toBe('');
    expect(truncateContent(undefined as any)).toBe('');
    expect(truncateContent('')).toBe('');
    expect(truncateContent('short', 0)).toBe('');
  });
});

# ── Tests for handleDelete  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

vi.mock('./api', () => ({
  deleteNote: vi.fn()
}))

const { deleteNote } = await vi.importSubject<typeof import('./api')>('./api')

vi.mock('./utils', () => ({
  showAlert: vi.fn()
}))

const { showAlert } = await vi.importSubject<typeof import('./utils')>('./utils')

import { handleDelete } from './handler'

describe('handleDelete', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('should handle happy path when event has a valid note id', async () => {
    const mockEvent = {
      target: { dataset: { id: 'note-123' } }
    } as any

    await handleDelete(mockEvent as Event)

    expect(deleteNote).toHaveBeenCalledWith('note-123')
    expect(showAlert).toHaveBeenCalledWith('Note deleted successfully')
  })

  it('should handle edge case when event target has no dataset id', async () => {
    const mockEvent = {
      target: {}
    } as any

    await handleDelete(mockEvent as Event)

    expect(deleteNote).not.toHaveBeenCalled()
    expect(showAlert).toHaveBeenCalledWith('Note id missing')
  })

  it('should handle null/empty values when event is null or undefined', async () => {
    await expect(handleDelete(null as unknown as Event)).resolves.not.toThrow()
    await expect(handleDelete(undefined as unknown as Event)).resolves.not.toThrow()
  })
})