/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

// Assuming the function is exported from a module named 'tagUtils'
import { normalizeTags } from './tagUtils'

describe('normalizeTags', () => {
  it('should handle happy path', () => {
    const input = ['  TagOne  ', 'TAGONE', 'TagTwo']
    const result = normalizeTags(input)
    expect(result).toEqual(['tagone', 'tagtwo'])
  })

  it('should handle edge case', () => {
    const input = ['  ', '   TagThree   ', 'TAGTHREE']
    const result = normalizeTags(input)
    expect(result).toEqual(['tagthree'])
  })

  it('should handle null/empty', () => {
    const resultDefault = normalizeTags()
    const resultEmptyArray = normalizeTags([])
    const resultNull = normalizeTags(null as any)
    const resultUndefined = normalizeTags(undefined as any)
    const resultEmptyString = normalizeTags([''])
    expect(resultDefault).toEqual([])
    expect(resultEmptyArray).toEqual([])
    expect(resultNull).toEqual([])
    expect(resultUndefined).toEqual([])
    expect(resultEmptyString).toEqual([])
  })
})

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { sortNotesByUpdatedAt } from './sortNotesByUpdatedAt';

describe('sortNotesByUpdatedAt', () => {
  beforeEach(() => {
    // reset any mocks if added later
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path by sorting notes from newest to oldest based on updatedAt', () => {
    const notes = [
      { id: 1, title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
      { id: 2, title: 'Note B', updatedAt: '2023-01-03T12:00:00Z' },
      { id: 3, title: 'Note C', updatedAt: '2023-01-02T08:30:00Z' },
    ];

    const sorted = sortNotesByUpdatedAt(notes);

    expect(sorted).toEqual([
      { id: 2, title: 'Note B', updatedAt: '2023-01-03T12:00:00Z' },
      { id: 3, title: 'Note C', updatedAt: '2023-01-02T08:30:00Z' },
      { id: 1, title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
    ]);
  });

  it('should handle edge case where notes have identical updatedAt timestamps', () => {
    const notes = [
      { id: 1, title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
      { id: 2, title: 'Note B', updatedAt: '2023-01-01T10:00:00Z' },
    ];

    const sorted = sortNotesByUpdatedAt(notes);

    // When timestamps are equal, original order should be preserved (stable sort)
    expect(sorted).toEqual([
      { id: 1, title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
      { id: 2, title: 'Note B', updatedAt: '2023-01-01T10:00:00Z' },
    ]);
  });

  it('should handle null/empty inputs gracefully', () => {
    // @ts-expect-error intentionally passing undefined
    expect(sortNotesByUpdatedAt(undefined)).toEqual([]);
    // @ts-expect-error intentionally passing null
    expect(sortNotesByUpdatedAt(null)).toEqual([]);
    expect(sortNotesByUpdatedAt([])).toEqual([]);
    expect(sortNotesByUpdatedAt('')).toEqual([]);
    expect(sortNotesByUpdatedAt(0 as any)).toEqual([]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect } from 'vitest';

// Assuming the implementation is imported from the module where it is defined
import { matchesSearchQuery } from './matchesSearchQuery';

describe('matchesSearchQuery', () => {
  // Happy path: typical note and query match
  it('should handle happy path where the query is found in the note title', () => {
    const note = { title: 'Meeting notes', content: 'Discuss project timeline' };
    const query = 'meeting';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  // Edge case: query matches content case-insensitively and query is a substring
  it('should handle edge case where the query is found in the note content with different casing', () => {
    const note = { title: 'Todo', content: 'Buy Milk and Bread' };
    const query = 'milk';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  // Null/empty inputs: query is empty string, undefined, null, or note fields are missing/empty
  it('should handle null/empty inputs and return false when nothing can be matched', () => {
    // Empty query
    const note1 = { title: 'Random', content: 'Some text' };
    expect(matchesSearchQuery(note1, '')).toBe(false);
    // Undefined query
    const note2 = { title: 'Random', content: 'Some text' };
    // @ts-ignore – intentionally passing undefined to test behavior
    expect(matchesSearchQuery(note2, undefined)).toBe(false);
    // Null query
    // @ts-ignore – intentionally passing null to test behavior
    expect(matchesSearchQuery(note2, null)).toBe(false);
    // Empty note fields
    const note3 = { title: '', content: '' };
    const query = 'anything';
    expect(matchesSearchQuery(note3, query)).toBe(false);
  });
});

# ── Tests for countWords  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { countWords } from './countWords';

describe('countWords', () => {
  beforeEach(() => {
    // No external dependencies to mock for this pure function
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path with a regular sentence', () => {
    const text = 'The quick brown fox jumps over the lazy dog';
    const result = countWords(text);
    expect(result).toBe(9);
  });

  it('should handle edge case with multiple spaces and newline characters', () => {
    const text = '   Hello   world\nthis\tis   a test  ';
    const result = countWords(text);
    // Words: Hello, world, this, is, a, test = 6
    expect(result).toBe(6);
  });

  it('should handle null/empty inputs gracefully', () => {
    // undefined
    expect(countWords(undefined as any)).toBe(0);
    // null
    expect(countWords(null as any)).toBe(0);
    // empty string
    expect(countWords('')).toBe(0);
    // numeric zero (should be treated as non‑string)
    expect(countWords(0 as any)).toBe(0);
  });
});