/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// Import the module under test — path is relative to tests/unit/
// import { NoteList } from '../../src/components/NoteList';



// ── Tests for NoteList  ──

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { NoteList } from '../../src/components/NoteList';

describe('NoteList component', () => {
  // Happy path: component renders without crashing and calls onSelectNote when a note is clicked
  it('should handle happy path', () => {
    const mockSelect = vi.fn();
    render(<NoteList onSelectNote={mockSelect} selectedNoteId={1} />);

    // Assuming each note is rendered as a button with text 'Note 1', 'Note 2', etc.
    const noteButton = screen.getByText(/Note/);
    fireEvent.click(noteButton);

    expect(mockSelect).toHaveBeenCalled();
    expect(mockSelect.mock.calls[0][0]).toBeDefined(); // the selected note id or object
  });

  // Edge case: selectedNoteId is one that does not match any note; component should still render
  it('should handle edge case', () => {
    const mockSelect = vi.fn();
    render(<NoteList onSelectNote={mockSelect} selectedNoteId={999} />);

    // The component should still contain note items even if none is selected
    const noteButtons = screen.queryAllByText(/Note/);
    expect(noteButtons.length).toBeGreaterThan(0);
  });

  // Null / empty: onSelectNote is undefined and selectedNoteId is null/empty string
  it('should handle null/empty props', () => {
    render(<NoteList onSelectNote={undefined as any} selectedNoteId={null as any} />);

    // The component should still render note items without throwing
    const noteButtons = screen.queryAllByText(/Note/);
    expect(noteButtons.length).toBeGreaterThan(0);

    // Ensure no errors are thrown when clicking (no handler to call)
    const noteButton = screen.getByText(/Note/);
    fireEvent.click(noteButton);

    // Since onSelectNote is undefined, nothing should happen but no crash
    expect(true).toBeTruthy();
  });
});