/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteList';



# ── Tests for NoteList  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup } from '@testing-library/react';
import NoteList from './NoteList';

describe('NoteList Component', () => {
  const notesMock = [
    { id: '1', title: 'First note' },
    { id: '2', title: 'Second note' },
  ];

  beforeEach(() => {
    // Mock any internal data fetching if NoteList uses a separate module
    // Example: vi.mock('../hooks/useNotes', () => ({
    //   useNotes: () => ({ notes: notesMock, loading: false }),
    // }));
  });

  afterEach(() => {
    cleanup();
    vi.restoreAllMocks();
  });

  it('should handle happy path: render notes and trigger onSelectNote on click', () => {
    const onSelectNote = vi.fn();

    render(<NoteList onSelectNote={onSelectNote} selectedNoteId={null} />);

    // Expect all notes to be rendered
    notesMock.forEach((note) => {
      expect(screen.getByText(note.title)).toBeInTheDocument();
    });

    // Click the first note
    fireEvent.click(screen.getByText(notesMock[0].title));

    // Callback should be called with the id of the clicked note
    expect(onSelectNote).toHaveBeenCalledOnce();
    expect(onSelectNote).toHaveBeenCalledWith(notesMock[0].id);
  });

  it('should handle edge case: highlight the selected note', () => {
    const onSelectNote = vi.fn();

    render(
      <NoteList
        onSelectNote={onSelectNote}
        selectedNoteId={notesMock[1].id}
      />
    );

    const selectedNoteElement = screen.getByText(notesMock[1].title);
    // Assuming selected note receives a CSS class like "selected"
    expect(selectedNoteElement).toHaveClass('selected');

    // Non‑selected note should not have the class
    const otherNoteElement = screen.getByText(notesMock[0].title);
    expect(otherNoteElement).not.toHaveClass('selected');
  });

  it('should handle null/empty props: render nothing and not crash', () => {
    const onSelectNote = vi.fn();

    // Render with undefined selectedNoteId and no notes (simulate empty list)
    render(<NoteList onSelectNote={onSelectNote} selectedNoteId={undefined} />);

    // Component should not throw and render a fallback (e.g., "No notes")
    // Adjust the expectation based on actual fallback implementation
    const fallback = screen.queryByText(/no notes/i);
    expect(fallback).toBeInTheDocument();

    // Ensure callback is never called when there is nothing to click
    expect(onSelectNote).not.toHaveBeenCalled();
  });
});