/**
 * Auto-generated tests for src/hooks/useNoteEditor.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../useNoteEditor';



# ── Tests for useNoteEditor  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { renderHook, act } from '@testing-library/react-hooks';
import { useNoteEditor } from './useNoteEditor';

// Mock any external modules the hook might depend on
vi.mock('./noteService', () => ({
  createNote: vi.fn(),
  fetchNote: vi.fn(),
}));

import { createNote, fetchNote } from './noteService';

describe('useNoteEditor', () => {
  const onNoteCreated = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path: edit existing note and create new note when no ID', () => {
    // Arrange
    const selectedNoteId = 'note-123';
    (fetchNote as any).mockResolvedValue({ id: selectedNoteId, content: 'Initial content' });
    (createNote as any).mockResolvedValue({ id: 'note-456', content: '' });

    const { result, waitForNextUpdate } = renderHook(() =>
      useNoteEditor({ selectedNoteId, onNoteCreated })
    );

    // Wait for the note to be fetched
    return waitForNextUpdate().then(() => {
      // Act: simulate editing
      act(() => {
        result.current.setContent('Updated content');
        result.current.save();
      });

      // Assert
      expect(fetchNote).toHaveBeenCalledOnce();
      expect(fetchNote).toHaveBeenCalledWith(selectedNoteId);
      expect(onNoteCreated).toHaveBeenCalledWith({
        id: selectedNoteId,
        content: 'Updated content',
      });
    });
  });

  it('should handle edge case: empty content should still trigger save without error', () => {
    // Arrange
    const selectedNoteId = 'note-789';
    (fetchNote as any).mockResolvedValue({ id: selectedNoteId, content: 'Some content' });

    const { result, waitForNextUpdate } = renderHook(() =>
      useNoteEditor({ selectedNoteId, onNoteCreated })
    );

    return waitForNextUpdate().then(() => {
      // Act: set empty content and save
      act(() => {
        result.current.setContent('');
        result.current.save();
      });

      // Assert
      expect(onNoteCreated).toHaveBeenCalledWith({
        id: selectedNoteId,
        content: '',
      });
    });
  });

  it('should handle null/empty inputs: create a new note when selectedNoteId is null or undefined', async () => {
    // Arrange
    (createNote as any).mockResolvedValue({ id: 'new-note', content: '' });

    const { result } = renderHook(() =>
      useNoteEditor({ selectedNoteId: null as any, onNoteCreated })
    );

    // Act: directly save without fetching an existing note
    await act(async () => {
      await result.current.save();
    });

    // Assert
    expect(createNote).toHaveBeenCalledOnce();
    expect(onNoteCreated).toHaveBeenCalledWith({
      id: 'new-note',
      content: '',
    });
  });
});