/**
 * Auto-generated tests for src/components/NoteEditor.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteEditor';



// ── Tests for NoteEditor  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup } from '@testing-library/react';
import NoteEditor from '@/components/NoteEditor';

describe('NoteEditor Component', () => {
  const mockOnNoteCreated = vi.fn();

  beforeEach(() => {
    mockOnNoteCreated.mockReset();
  });

  afterEach(() => {
    cleanup();
  });

  it('should handle happy path with valid selectedNoteId and callback', () => {
    render(<NoteEditor selectedNoteId="note-123" onNoteCreated={mockOnNoteCreated} />);
    // Assuming the component renders a textarea for editing
    const textarea = screen.getByRole('textbox');
    expect(textarea).toBeInTheDocument();

    // Simulate creating a note
    fireEvent.change(textarea, { target: { value: 'New note content' } });
    fireEvent.click(screen.getByRole('button', { name: /save/i }));

    expect(mockOnNoteCreated).toHaveBeenCalledTimes(1);
    expect(mockOnNoteCreated).toHaveBeenCalledWith(expect.objectContaining({
      id: expect.any(String),
      content: 'New note content',
    }));
  });

  it('should handle edge case when selectedNoteId is an empty string', () => {
    render(<NoteEditor selectedNoteId="" onNoteCreated={mockOnNoteCreated} />);
    // The component should still render the editor UI
    const textarea = screen.getByRole('textbox');
    expect(textarea).toBeInTheDocument();
    // No note should be pre‑loaded
    expect(textarea).toHaveValue('');
  });

  it('should handle null/undefined/empty inputs gracefully', () => {
    // selectedNoteId as null
    render(<NoteEditor selectedNoteId={null as any} onNoteCreated={mockOnNoteCreated} />);
    const textarea = screen.getByRole('textbox');
    expect(textarea).toBeInTheDocument();
    expect(textarea).toHaveValue('');

    // onNoteCreated as undefined (should not crash on submit)
    cleanup();
    render(<NoteEditor selectedNoteId="note-456" onNoteCreated={undefined as any} />);
    const btn = screen.getByRole('button', { name: /save/i });
    fireEvent.click(btn);
    // No error should be thrown; simply no callback invocation
    expect(true).toBe(true);
  });
});