/**
 * Auto-generated tests for src/components/NoteList.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteList';



// ── Tests for NoteList  ──

import { describe, it, expect, vi, beforeEach, afterEach, render, screen, fireEvent } from 'vitest';
import NoteList from '../NoteList';

// Mock the hook or module that provides notes.
// Adjust the path to the actual implementation in the project.
vi.mock('../hooks/useNotes', () => ({
  useNotes: vi.fn()
}));

// Import the mocked hook to control its return value.
import { useNotes } from '../hooks/useNotes';

describe('NoteList component', () => {
  const mockOnSelectNote = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path and render note items when notes are available', async () => {
    // Arrange: mock the hook to return a few notes.
    (useNotes as vi.Mock).mockReturnValue([
      { id: '1', title: 'First Note', content: 'Content A' },
      { id: '2', title: 'Second Note', content: 'Content B' }
    ]);

    // Act: render the component.
    render(<NoteList onSelectNote={mockOnSelectNote} selectedNoteId={null} />);

    // Assert: the component renders the correct number of note items.
    const items = await screen.findAllByTestId('note-item');
    expect(items).toHaveLength(2);

    // Simulate selecting a note and verify callback.
    fireEvent.click(items[0]);
    expect(mockOnSelectNote).toHaveBeenCalledWith('1');
  });

  it('should handle edge case where no notes are returned and show an empty state', async () => {
    // Arrange: mock the hook to return an empty array.
    (useNotes as vi.Mock).mockReturnValue([]);

    // Act: render the component.
    render(<NoteList onSelectNote={mockOnSelectNote} selectedNoteId={null} />);

    // Assert: no items are rendered and an empty message is shown.
    const items = screen.queryAllByTestId('note-item');
    expect(items).toHaveLength(0);

    const emptyMessage = await screen.findByText(/no notes found/i);
    expect(emptyMessage).toBeInTheDocument();
  });

  it('should handle null/empty props and not crash', async () => {
    // Arrange: mock the hook to return a single note.
    (useNotes as vi.Mock).mockReturnValue([
      { id: '1', title: 'Only Note', content: 'Some content' }
    ]);

    // Act & Assert: render with undefined onSelectNote and selectedNoteId.
    expect(() => {
      render(<NoteList onSelectNote={undefined as any} selectedNoteId={undefined as any} />);
    }).not.toThrow();

    // Verify that the note item still renders but clicking it should not call undefined handler.
    const item = await screen.findByTestId('note-item');
    fireEvent.click(item);
    expect(mockOnSelectNote).not.toHaveBeenCalled();
  });
});