/**
 * Auto-generated tests for src/components/NoteEditor.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteEditor';



# ── Tests for NoteEditor  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, fireEvent, screen, cleanup } from '@testing-library/react';
import NoteEditor from '@/components/NoteEditor';

// Mock any child components or hooks used inside NoteEditor if needed
vi.mock('@/hooks/useNotes', () => ({
  useNotes: vi.fn(() => ({
    createNote: vi.fn(),
    getNoteById: vi.fn(),
  })),
}));

describe('NoteEditor Component', () => {
  const onNoteCreatedMock = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    cleanup();
  });

  it('should handle happy path: render editor for a valid selectedNoteId and create a note on save', async () => {
    const selectedNoteId = 'note-123';
    render(<NoteEditor selectedNoteId={selectedNoteId} onNoteCreated={onNoteCreatedMock} />);

    // Assume there is a textarea/input for note content
    const textarea = screen.getByRole('textbox');
    expect(textarea).toBeInTheDocument();

    // Simulate user typing
    fireEvent.change(textarea, { target: { value: 'Test note content' } });

    // Assume there is a save button
    const saveButton = screen.getByRole('button', { name: /save/i });
    fireEvent.click(saveButton);

    // Expect the callback to be called with the new note data
    expect(onNoteCreatedMock).toHaveBeenCalledTimes(1);
    expect(onNoteCreatedMock).toHaveBeenCalledWith(
      expect.objectContaining({
        id: expect.any(String),
        content: 'Test note content',
      })
    );
  });

  it('should handle edge case: render with empty selectedNoteId and allow creating a new note', () => {
    // Edge case where selectedNoteId is an empty string (new note mode)
    render(<NoteEditor selectedNoteId={''} onNoteCreated={onNoteCreatedMock} />);

    const textarea = screen.getByRole('textbox');
    expect(textarea).toBeInTheDocument();
    expect(textarea).toHaveValue(''); // should start empty

    fireEvent.change(textarea, { target: { value: 'Edge case note' } });

    const saveButton = screen.getByRole('button', { name: /save/i });
    fireEvent.click(saveButton);

    expect(onNoteCreatedMock).toHaveBeenCalledTimes(1);
    expect(onNoteCreatedMock).toHaveBeenCalledWith(
      expect.objectContaining({
        id: expect.any(String),
        content: 'Edge case note',
      })
    );
  });

  it('should handle null/empty props: render without crashing when selectedNoteId is null/undefined and onNoteCreated is not provided', () => {
    // Render with null selectedNoteId and no onNoteCreated callback
    // @ts-expect-error intentionally passing undefined props to test robustness
    render(<NoteEditor selectedNoteId={null} />);

    const textarea = screen.getByRole('textbox');
    expect(textarea).toBeInTheDocument();

    fireEvent.change(textarea, { target: { value: 'Some content' } });

    const saveButton = screen.getByRole('button', { name: /save/i });
    fireEvent.click(saveButton);

    // When onNoteCreated is missing, the component should not throw
    // and simply not call any callback
    // No expectation on a mock here; just ensure no error occurs
    expect(true).toBe(true);
  });
});