/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../noteUtils';



# ── Tests for normalizeTags  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { normalizeTags } from './utils';

describe('normalizeTags', () => {
  // Happy path: typical array of strings
  it('should handle happy path with normal tags', () => {
    const input = ['JavaScript', 'TypeScript', 'Vitest'];
    const result = normalizeTags(input);
    // Assuming the function returns a deduped, trimmed, lower‑cased array
    expect(result).toEqual(['javascript', 'typescript', 'vitest']);
  });

  // Edge case: tags containing whitespace, duplicates, and mixed case
  it('should handle edge case with whitespace, duplicates and mixed case', () => {
    const input = ['  React  ', 'react', 'REACT', 'Node', 'node '];
    const result = normalizeTags(input);
    // Expect each tag to be trimmed, lower‑cased and duplicates removed
    expect(result).toEqual(['react', 'node']);
  });

  // Null/empty handling
  it('should handle null/empty inputs gracefully', () => {
    // undefined / null / empty string / empty array / zero
    expect(normalizeTags(undefined)).toEqual([]);
    expect(normalizeTags(null as any)).toEqual([]);
    expect(normalizeTags('' as any)).toEqual([]);
    expect(normalizeTags(0 as any)).toEqual([]);
    expect(normalizeTags([])).toEqual([]);
  });
});

# ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { sortNotesByUpdatedAt } from './path-to-your-module';

describe('sortNotesByUpdatedAt', () => {
  it('should handle happy path and sort notes by updatedAt descending', () => {
    const notes = [
      { id: 1, title: 'Note A', updatedAt: 1620000000000 },
      { id: 2, title: 'Note B', updatedAt: 1625000000000 },
      { id: 3, title: 'Note C', updatedAt: 1615000000000 },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    expect(sorted).toEqual([
      { id: 2, title: 'Note B', updatedAt: 1625000000000 },
      { id: 1, title: 'Note A', updatedAt: 1620000000000 },
      { id: 3, title: 'Note C', updatedAt: 1615000000000 },
    ]);
  });

  it('should handle edge case where notes have identical updatedAt values', () => {
    const notes = [
      { id: 1, title: 'Note A', updatedAt: 1620000000000 },
      { id: 2, title: 'Note B', updatedAt: 1620000000000 },
      { id: 3, title: 'Note C', updatedAt: 1625000000000 },
    ];
    const sorted = sortNotesByUpdatedAt(notes);
    // Expect the note with the newest timestamp first, others keep original order
    expect(sorted[0]).toEqual({ id: 3, title: 'Note C', updatedAt: 1625000000000 });
    expect(sorted.slice(1)).toEqual([
      { id: 1, title: 'Note A', updatedAt: 1620000000000 },
      { id: 2, title: 'Note B', updatedAt: 1620000000000 },
    ]);
  });

  it('should handle null/empty inputs gracefully', () => {
    // @ts-ignore testing runtime behavior with null
    expect(sortNotesByUpdatedAt(null)).toEqual([]);
    // @ts-ignore testing runtime behavior with undefined
    expect(sortNotesByUpdatedAt(undefined)).toEqual([]);
    expect(sortNotesByUpdatedAt([])).toEqual([]);
    // Empty string is not a valid notes array; expect fallback to empty array
    // @ts-ignore intentional misuse
    expect(sortNotesByUpdatedAt('')).toEqual([]);
  });
});

# ── Tests for matchesSearchQuery  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assume the implementation is imported from the current module
import { matchesSearchQuery } from './matchesSearchQuery';

describe('matchesSearchQuery', () => {
  const sampleNote = {
    title: 'Meeting Notes',
    body: 'Discuss project timeline and milestones.',
    tags: ['meeting', 'project'],
  };

  it('should handle happy path: query matches note title', () => {
    const result = matchesSearchQuery(sampleNote, 'Meeting');
    expect(result).toBe(true);
  });

  it('should handle edge case: query matches within note body but not title', () => {
    const result = matchesSearchQuery(sampleNote, 'timeline');
    expect(result).toBe(true);
  });

  it('should handle null/empty: query is empty string or null', () => {
    const resultEmpty = matchesSearchQuery(sampleNote, '');
    const resultNull = matchesSearchQuery(sampleNote, null as unknown as string);
    expect(resultEmpty).toBe(false);
    expect(resultNull).toBe(false);
  });
});

# ── Tests for countWords  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { countWords } from './countWords';

describe('countWords', () => {
  it('should handle happy path - normal sentence', () => {
    const text = 'The quick brown fox jumps over the lazy dog';
    const result = countWords(text);
    expect(result).toBe(9);
  });

  it('should handle edge case - punctuation and multiple spaces', () => {
    const text = 'Hello, world!   This   is   a-test.';
    const result = countWords(text);
    // Words are: Hello, world, This, is, a-test => 5
    expect(result).toBe(5);
  });

  it('should handle null/empty - null, undefined, empty string, zero', () => {
    // @ts-ignore
    expect(countWords(null)).toBe(0);
    // @ts-ignore
    expect(countWords(undefined)).toBe(0);
    expect(countWords('')).toBe(0);
    expect(countWords('0')).toBe(1);
  });
});