/**
 * Auto-generated tests for src/modules/noteUtils.js
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// Import the module under test — path is relative to tests/unit/
// import { noteUtils } from '../../src/modules/noteUtils';



// ── Tests for normalizeTags  ──

import { describe, it, expect } from 'vitest';
import { normalizeTags } from '../../src/modules/noteUtils';

describe('normalizeTags', () => {
  it('should handle happy path', () => {
    const input = ['TagOne', ' tagTwo ', 'TAGThree'];
    const output = normalizeTags(input);
    // Assuming normalizeTags trims and lowercases tags
    expect(output).toEqual(['tagone', 'tagtwo', 'tagthree']);
  });

  it('should handle edge case', () => {
    const input = ['123', '!!', ' mixed CASE '];
    const output = normalizeTags(input);
    expect(output).toEqual(['123', '!!', 'mixed case']);
  });

  it('should handle null/empty inputs', () => {
    // No argument defaults to empty array
    expect(normalizeTags()).toEqual([]);
    // Explicit null or undefined should also result in empty array
    expect(normalizeTags(null as any)).toEqual([]);
    expect(normalizeTags(undefined as any)).toEqual([]);
    // Empty array input
    expect(normalizeTags([])).toEqual([]);
  });
});

// ── Tests for sortNotesByUpdatedAt  ──

import { describe, it, expect } from 'vitest';
import { sortNotesByUpdatedAt } from '../../src/modules/noteUtils';

describe('sortNotesByUpdatedAt', () => {
  it('should handle happy path by sorting notes descending by updatedAt', () => {
    const notes = [
      { id: 1, title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
      { id: 2, title: 'Note B', updatedAt: '2023-01-02T09:00:00Z' },
      { id: 3, title: 'Note C', updatedAt: '2023-01-01T12:00:00Z' },
    ];

    const sorted = sortNotesByUpdatedAt(notes);

    expect(sorted).toEqual([
      { id: 2, title: 'Note B', updatedAt: '2023-01-02T09:00:00Z' },
      { id: 3, title: 'Note C', updatedAt: '2023-01-01T12:00:00Z' },
      { id: 1, title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
    ]);
  });

  it('should handle edge case with identical updatedAt values', () => {
    const notes = [
      { id: 1, title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
      { id: 2, title: 'Note B', updatedAt: '2023-01-01T10:00:00Z' },
      { id: 3, title: 'Note C', updatedAt: '2023-01-01T09:00:00Z' },
    ];

    const sorted = sortNotesByUpdatedAt(notes);

    // Expect notes with same timestamp to retain original relative order (stable sort)
    expect(sorted).toEqual([
      { id: 1, title: 'Note A', updatedAt: '2023-01-01T10:00:00Z' },
      { id: 2, title: 'Note B', updatedAt: '2023-01-01T10:00:00Z' },
      { id: 3, title: 'Note C', updatedAt: '2023-01-01T09:00:00Z' },
    ]);
  });

  it('should handle null/empty inputs gracefully', () => {
    // undefined (default parameter)
    expect(sortNotesByUpdatedAt()).toEqual([]);

    // null input
    // @ts-expect-error testing runtime behavior with null
    expect(sortNotesByUpdatedAt(null)).toEqual([]);

    // empty array
    expect(sortNotesByUpdatedAt([])).toEqual([]);
  });
});

// ── Tests for matchesSearchQuery  ──

import { describe, it, expect } from 'vitest';
import { matchesSearchQuery } from '../../src/modules/noteUtils';

describe('matchesSearchQuery', () => {
  it('should handle happy path: return true for matching note and query', () => {
    const note = { title: 'Meeting Notes', content: 'Discuss project timeline.' };
    const query = 'project';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  it('should handle edge case: partial match in title or content', () => {
    const note = { title: 'Daily Standup', content: 'Sprint review points.' };
    const query = 'stand';
    const result = matchesSearchQuery(note, query);
    expect(result).toBe(true);
  });

  it('should handle null/empty: return false for null query or empty note fields', () => {
    const note = { title: '', content: '' };
    const result = matchesSearchQuery(note, null as any);
    expect(result).toBe(false);

    const emptyNote = null as any;
    const resultEmptyNote = matchesSearchQuery(emptyNote, 'anything');
    expect(resultEmptyNote).toBe(false);
  });
});

// ── Tests for countWords  ──

import { describe, it, expect } from 'vitest';
import { countWords } from '../../src/modules/noteUtils';

describe('countWords', () => {
  it('should handle happy path', () => {
    const text = 'Hello world';
    const result = countWords(text);
    expect(result).toBe(2);
  });

  it('should handle edge case', () => {
    const text = 'Hello, world!  This   is a test.';
    const result = countWords(text);
    expect(result).toBe(6);
  });

  it('should handle null/empty', () => {
    expect(countWords(null as unknown as string)).toBe(0);
    expect(countWords(undefined as unknown as string)).toBe(0);
    expect(countWords('')).toBe(0);
    expect(countWords(0 as unknown as string)).toBe(0);
  });
});