/**
 * Auto-generated tests for src/components/NoteItem.jsx
 * Generated by OpsMind AI Testing Agent
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
// TODO: update import path to match project structure
// import { ... } from '../NoteItem';



# ── Tests for NoteItem  ──

import { describe, it, expect, vi } from 'vitest';
import { render, fireEvent } from '@testing-library/react';
import NoteItem from './NoteItem';

describe('NoteItem Component', () => {
  const mockOnSelect = vi.fn();

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should handle happy path: renders note content and calls onSelect when clicked', () => {
    const note = { id: 1, title: 'Test Note', content: 'Hello World' };
    const { getByText, container } = render(
      <NoteItem note={note} isSelected={false} onSelect={mockOnSelect} />
    );

    // note title and content should be rendered
    expect(getByText('Test Note')).toBeInTheDocument();
    expect(getByText('Hello World')).toBeInTheDocument();

    // clicking the root element should trigger onSelect
    fireEvent.click(container.firstChild as HTMLElement);
    expect(mockOnSelect).toHaveBeenCalledOnce();
  });

  it('should handle edge case: renders correctly when isSelected is true', () => {
    const note = { id: 2, title: 'Selected Note', content: 'Edge case' };
    const { container } = render(
      <NoteItem note={note} isSelected={true} onSelect={mockOnSelect} />
    );

    // Assuming selected state adds a CSS class like "selected"
    expect(container.firstChild).toHaveClass('selected');
    // onSelect should still be callable
    fireEvent.click(container.firstChild as HTMLElement);
    expect(mockOnSelect).toHaveBeenCalledOnce();
  });

  it('should handle null/empty inputs gracefully', () => {
    // Render with null/undefined/empty values
    const { container } = render(
      <NoteItem note={null as any} isSelected={false} onSelect={mockOnSelect} />
    );

    // Component should render without throwing; likely renders nothing or placeholder
    expect(container.firstChild).toBeTruthy();

    // Click should still invoke onSelect (if component renders a clickable wrapper)
    fireEvent.click(container.firstChild as HTMLElement);
    expect(mockOnSelect).toHaveBeenCalledOnce();
  });
});

# ── Tests for formatDate  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { formatDate } from './formatDate';

describe('formatDate', () => {
  it('should handle happy path with a valid ISO string', () => {
    const iso = '2023-08-15T12:34:56Z';
    const result = formatDate(iso);
    expect(result).toBe('August 15, 2023');
  });

  it('should handle edge case with midnight and timezone offset', () => {
    const iso = '2023-12-31T00:00:00-0500';
    const result = formatDate(iso);
    expect(result).toBe('December 31, 2023');
  });

  it('should handle null/empty inputs gracefully', () => {
    expect(formatDate(null)).toBeNull();
    expect(formatDate(undefined)).toBeNull();
    expect(formatDate('')).toBeNull();
    expect(formatDate('0')).toBeNull();
  });
});

# ── Tests for truncateContent  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Assuming the function is exported from a module named 'utils'
import { truncateContent } from './utils';

describe('truncateContent', () => {
  beforeEach(() => {
    // Reset any mocks or state before each test if needed
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path by truncating a long string to the default maxLength', () => {
    const longString = 'a'.repeat(200);
    const result = truncateContent(longString);
    expect(result).toBeInstanceOf(String);
    expect(result.length).toBeLessThanOrEqual(80);
    // Expect the result to be a prefix of the original string
    expect(longString.startsWith(result)).toBe(true);
  });

  it('should handle edge case when content length equals maxLength', () => {
    const exactLengthString = 'b'.repeat(50);
    const result = truncateContent(exactLengthString, 50);
    // Should return the original string unchanged
    expect(result).toBe(exactLengthString);
    expect(result.length).toBe(50);
  });

  it('should handle null/empty inputs gracefully', () => {
    // null input
    // @ts-expect-error testing runtime behavior with null
    expect(() => truncateContent(null)).not.toThrow();
    // undefined input
    // @ts-expect-error testing runtime behavior with undefined
    expect(() => truncateContent(undefined)).not.toThrow();
    // empty string
    expect(truncateContent('')).toBe('');
    // numeric zero (should be treated as falsy and converted to string)
    // @ts-expect-error testing runtime behavior with number
    expect(truncateContent(0)).toBe('0');
  });
});

# ── Tests for handleDelete  ──

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { handleDelete } from './your-module'; // adjust the path to where handleDelete is exported

describe('handleDelete', () => {
  let mockEvent: any;

  beforeEach(() => {
    mockEvent = {
      preventDefault: vi.fn(),
      target: { dataset: { id: '123' } },
    };
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should handle happy path by calling preventDefault and performing delete logic', () => {
    // Assuming handleDelete uses the id from event.target.dataset.id
    // and perhaps calls a delete function from another module.
    // We'll mock that dependency if it exists.
    const deleteItemMock = vi.fn();
    vi.mock('./your-module', async () => {
      const actual = await vi.importActual<any>('./your-module');
      return {
        ...actual,
        // replace the internal delete helper with a mock
        deleteItem: deleteItemMock,
      };
    });

    handleDelete(mockEvent);

    expect(mockEvent.preventDefault).toHaveBeenCalledOnce();
    expect(deleteItemMock).toHaveBeenCalledWith('123');
  });

  it('should handle edge case when id is missing but event is still valid', () => {
    mockEvent.target.dataset = {}; // no id present

    // Mock the internal delete function to ensure it's not called
    const deleteItemMock = vi.fn();
    vi.mock('./your-module', async () => {
      const actual = await vi.importActual<any>('./your-module');
      return {
        ...actual,
        deleteItem: deleteItemMock,
      };
    });

    handleDelete(mockEvent);

    expect(mockEvent.preventDefault).toHaveBeenCalledOnce();
    // Expect that deleteItem is not called because id is undefined
    expect(deleteItemMock).not.toHaveBeenCalled();
  });

  it('should handle null/empty event gracefully without throwing', () => {
    const nullEvent = null;
    const undefinedEvent = undefined;
    const emptyEvent = {};

    // Ensure no exceptions are thrown for each case
    expect(() => handleDelete(nullEvent)).not.toThrow();
    expect(() => handleDelete(undefinedEvent)).not.toThrow();
    expect(() => handleDelete(emptyEvent)).not.toThrow();

    // When event is not an object with preventDefault, ensure nothing is called
    // (no mock to check here because preventDefault does not exist)
  });
});